### ISSUE TITLE
Conflict errors transferring files to Cryptomator vault

### ISSUE THREAD

**Issue by cyberduck** [iterate-ch/cyberduck#11880]
> **79324f3** created the issue

**Problem Description:**

Attempting to transfer a large sum of data (100GB+) triggers an error message (image attached) randomly throughout the transfer process: 

![Q88Hy7l_d.webp](https://github-cyberduck-assets.s3.amazonaws.com/11880/Q88Hy7l_d.webp)
**Debug Log:**

```
Caused by: BackgroundException{class=class ch.cyberduck.core.exception.ConflictException, file=Path{path='/My Files/My Vault/d/DZ/JGIPWQZA2DS2YIW6MJDZNW3LLY27VT/7ww3ityh-LE7FsOwqVNUlafwmz6tNyVA.c9r', type=[directory, encrypted]}, message='Cannot create folder 7ww3ityh-LE7FsOwqVNUlafwmz6tNyVA.c9r.', detail='Conflict. The specified item name already exists.', cause='org.apache.http.client.HttpResponseException: status code: 409, reason phrase: Conflict. The specified item name already exists.'}
	at ch.cyberduck.core.http.HttpResponseExceptionMappingService.map(HttpResponseExceptionMappingService.java:57)
	at ch.cyberduck.core.http.HttpResponseExceptionMappingService.map(HttpResponseExceptionMappingService.java:44)
	at ch.cyberduck.core.onedrive.GraphExceptionMappingService.map(GraphExceptionMappingService.java:70)
	at ch.cyberduck.core.onedrive.GraphExceptionMappingService.map(GraphExceptionMappingService.java:37)
	at ch.cyberduck.core.AbstractExceptionMappingService.map(AbstractExceptionMappingService.java:52)
	at ch.cyberduck.core.onedrive.GraphExceptionMappingService.map(GraphExceptionMappingService.java:53)
	at ch.cyberduck.core.onedrive.features.GraphDirectoryFeature.mkdir(GraphDirectoryFeature.java:56)
	at ch.cyberduck.core.cryptomator.features.CryptoDirectoryV7Feature.mkdir(CryptoDirectoryV7Feature.java:63)
	at ch.cyberduck.core.vault.registry.VaultRegistryDirectoryFeature.mkdir(VaultRegistryDirectoryFeature.java:41)
	at ch.cyberduck.core.transfer.UploadTransfer.transfer(UploadTransfer.java:258)
	at ch.cyberduck.core.worker.AbstractTransferWorker$3.transferSegment(AbstractTransferWorker.java:417)
	... 10 more
Caused by: org.apache.http.client.HttpResponseException: status code: 409, reason phrase: Conflict. The specified item name already exists.
	... 19 more

```

-*Workarounds/Other Test Results:**

Attempting to transfer the same data to a non-encrypted vault in One Drive for Business works successfully without error.   

___
Attachments

* [`Q88Hy7l_d.webp`](https://github-cyberduck-assets.s3.amazonaws.com/11880/Q88Hy7l_d.webp) (21.2 KiB)

**Comment by dkocher** [comment]
I cannot reproduce the problem running [8.5.6](https://trac.cyberduck.io/milestone/8.5.6).
