### ISSUE TITLE
scp works, cyberducks fails with Interoperability failure

### ISSUE THREAD

**Issue by tcurdt** [iterate-ch/cyberduck#12832]
I have a pi zero running in my local LAN

    dropbear -V
    Dropbear v2020.81

from the cli I can `scp` no problem.

According the debug log it does seem that cyberduck also manages to auth - but then fails with an EOF and I don't understand the reason.

```
2022-01-27 17:31:10,682 [main] INFO  ch.cyberduck.core.preferences.PreferencesFactory - Running version 8.2.1.36773 (2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6)
...
022-01-27 17:31:59,867 [Thread-58] DEBUG net.schmizz.concurrent.Promise - Awaiting <<authenticated>>
2022-01-27 17:31:59,877 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.userauth.method.AuthPublickey - Attempting authentication using PKCS8KeyFile{resource=[PrivateKeyReaderResource] java.io.InputStreamReader@7e5ae88f}
2022-01-27 17:31:59,885 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.userauth.UserAuthImpl - Asking `publickey` method to handle USERAUTH_60 packet
2022-01-27 17:31:59,885 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.userauth.method.AuthPublickey - Key acceptable, sending signed request
2022-01-27 17:31:59,885 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.userauth.method.AuthPublickey - Attempting authentication using PKCS8KeyFile{resource=[PrivateKeyReaderResource] java.io.InputStreamReader@7e5ae88f}
2022-01-27 17:31:59,917 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.transport.TransportImpl - Setting active service to ssh-connection
2022-01-27 17:31:59,917 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.concurrent.Promise - Setting <<authenticated>> to `true`
2022-01-27 17:31:59,917 [Thread-58] DEBUG net.schmizz.sshj.userauth.UserAuthImpl - `publickey` auth successful
2022-01-27 17:31:59,917 [Thread-58] INFO  ch.cyberduck.core.sftp.SFTPSession - Authentication succeeded with credentials Credentials{user='root', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/tcurdt/.ssh/id_rsa'}} and authentication method ch.cyberduck.core.sftp.auth.SFTPPublicKeyAuthentication@36d654c9
2022-01-27 17:31:59,920 [Thread-58] DEBUG net.schmizz.sshj.connection.ConnectionImpl - Attaching `session` channel (#0)
2022-01-27 17:31:59,921 [Thread-58] DEBUG net.schmizz.concurrent.Promise - Awaiting <<chan#0 / open>>
2022-01-27 17:31:59,927 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.connection.channel.direct.SessionChannel - Initialized - < session channel: id=0, recipient=0, localWin=[winSize=2097152], remoteWin=[winSize=65536] >
2022-01-27 17:31:59,927 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.concurrent.Promise - Setting <<chan#0 / open>> to `SOME`
2022-01-27 17:31:59,927 [Thread-58] INFO  net.schmizz.sshj.connection.channel.direct.SessionChannel - Will request `sftp` subsystem
2022-01-27 17:31:59,927 [Thread-58] DEBUG net.schmizz.sshj.connection.channel.direct.SessionChannel - Sending channel request for `subsystem`
2022-01-27 17:31:59,927 [Thread-58] DEBUG net.schmizz.concurrent.Promise - Awaiting <<chan#0 / chanreq for subsystem>>
2022-01-27 17:31:59,938 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.concurrent.Promise - Setting <<chan#0 / chanreq for subsystem>> to `SOME`
2022-01-27 17:31:59,939 [Thread-58] DEBUG net.schmizz.sshj.connection.channel.Window$Remote - Consuming by 9 down to 65527
2022-01-27 17:31:59,957 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.connection.channel.Window$Local - Consuming by 62 down to 2097090
2022-01-27 17:31:59,959 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.connection.channel.direct.SessionChannel - Got EOF
2022-01-27 17:31:59,961 [Thread-58] WARN  ch.cyberduck.core.sftp.SFTPSession - Disconnected BY_APPLICATION
2022-01-27 17:31:59,961 [Thread-58] DEBUG net.schmizz.sshj.connection.ConnectionImpl - Notified of net.schmizz.sshj.transport.TransportException: [BY_APPLICATION] Disconnected
2022-01-27 17:31:59,961 [Thread-58] DEBUG net.schmizz.sshj.connection.channel.direct.SessionChannel - Channel #0 got notified of net.schmizz.sshj.transport.TransportException: [BY_APPLICATION] Disconnected
2022-01-27 17:31:59,961 [Thread-58] DEBUG net.schmizz.sshj.connection.ConnectionImpl - Forgetting `session` channel (#0)
2022-01-27 17:31:59,961 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.connection.channel.direct.SessionChannel - Got chan request for `exit-status`
2022-01-27 17:31:59,961 [Thread-58] DEBUG net.schmizz.concurrent.Promise - Setting <<chan#0 / close>> to `SOME`
2022-01-27 17:31:59,961 [Thread-58] DEBUG net.schmizz.sshj.transport.TransportImpl - Sending SSH_MSG_DISCONNECT: reason=[BY_APPLICATION], msg=[]
2022-01-27 17:31:59,962 [Thread-58] DEBUG net.schmizz.concurrent.Promise - Setting <<transport close>> to `SOME`
2022-01-27 17:31:59,962 [Thread-58] DEBUG ch.cyberduck.core.Session - Connection did close to Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, port=22, hostname='pi-zero', credentials=Credentials{user='root', oauth='OAuthTokens{accessToken='null', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=Local{path='/Users/tcurdt/.ssh/id_rsa'}}, uuid='null', nickname='null', defaultpath='null', workdir=null, labels=null}
2022-01-27 17:31:59,962 [sshj-Reader-/192.168.178.24:22] DEBUG net.schmizz.sshj.transport.Reader - Stopping
2022-01-27 17:31:59,962 [Thread-58] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=null, message='Interoperability failure', detail='EOF while reading packet.', cause='net.schmizz.sshj.sftp.SFTPException: EOF while reading packet'}
2022-01-27 17:31:59,963 [Thread-58] WARN  ch.cyberduck.core.threading.AbstractRetryCallable - No retry for failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=null, message='Interoperability failure', detail='EOF while reading packet.', cause='net.schmizz.sshj.sftp.SFTPException: EOF while reading packet'}
2022-01-27 17:31:59,963 [Thread-58] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=null, message='Interoperability failure', detail='EOF while reading packet.', cause='net.schmizz.sshj.sftp.SFTPException: EOF while reading packet'} running background task
java.lang.Exception: null
	at ch.cyberduck.core.threading.BackgroundCallable.<init>(BackgroundCallable.java:37) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.DefaultBackgroundExecutor.execute(DefaultBackgroundExecutor.java:68) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.AbstractController.background(AbstractController.java:72) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$29.run(BrowserController.java:3207) ~[osx-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$32.run(BrowserController.java:3334) ~[osx-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$33.cleanup(BrowserController.java:3353) ~[osx-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.BackgroundCallable$1.run(BackgroundCallable.java:75) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at org.rococoa.internal.MainThreadUtils$3.callback(MainThreadUtils.java:91) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:579) [jna-min-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:610) [jna-min-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-min-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-min-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-min-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:315) ~[jna-min-5.10.0.jar:5.10.0 (b0)]
	at org.rococoa.internal.MsgSendHandler.invoke(MsgSendHandler.java:114) ~[rococoa-core-0.9.1.jar:?]
	at com.sun.jna.Library$Handler.invoke(Library.java:263) ~[jna-min-5.10.0.jar:5.10.0 (b0)]
	at jdk.proxy2.$Proxy5.syntheticSendMessage(Unknown Source) ~[?:?]
	at org.rococoa.Foundation.send(Foundation.java:207) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.Foundation.send(Foundation.java:181) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.sendOnThisOrMainThread(ObjCObjectInvocationHandler.java:245) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.invokeCocoa(ObjCObjectInvocationHandler.java:212) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.intercept(ObjCObjectInvocationHandler.java:171) ~[rococoa-core-0.9.1.jar:?]
	at ch.cyberduck.binding.application.NSApplication$$ByRococoa.run(<generated>) ~[binding-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.ui.cocoa.MainApplication.main(MainApplication.java:122) ~[osx-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
Caused by: ch.cyberduck.core.exception.InteroperabilityException: Interoperability failure
	at ch.cyberduck.core.sftp.SFTPExceptionMappingService.map(SFTPExceptionMappingService.java:69) ~[ssh-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.sftp.SFTPSession.login(SFTPSession.java:264) ~[ssh-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.KeychainLoginService.authenticate(KeychainLoginService.java:175) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.LoginConnectionService.authenticate(LoginConnectionService.java:176) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.LoginConnectionService.connect(LoginConnectionService.java:167) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.LoginConnectionService.check(LoginConnectionService.java:110) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.pool.StatelessSessionPool.borrow(StatelessSessionPool.java:59) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.SessionBackgroundAction.run(SessionBackgroundAction.java:123) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.SessionBackgroundAction$1.call(SessionBackgroundAction.java:108) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.DefaultRetryCallable.call(DefaultRetryCallable.java:52) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.SessionBackgroundAction.call(SessionBackgroundAction.java:110) ~[core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.BackgroundCallable.run(BackgroundCallable.java:95) [core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:59) [core-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at ch.cyberduck.core.threading.DispatchExecutorService$InvocationFutureTask.run(DispatchExecutorService.java:281) [libcore-8.2.1.jar:2f66ca66589c71e3ef52ffa41ff141d93fdc7ab6]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) [rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:579) ~[jna-min-5.10.0.jar:5.10.0 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:610) ~[jna-min-5.10.0.jar:5.10.0 (b0)]
Caused by: net.schmizz.sshj.sftp.SFTPException: EOF while reading packet
	at net.schmizz.sshj.sftp.PacketReader.readIntoBuffer(PacketReader.java:55) ~[sshj-0.32.4.jar:?]
	at net.schmizz.sshj.sftp.PacketReader.getPacketLength(PacketReader.java:60) ~[sshj-0.32.4.jar:?]
	at net.schmizz.sshj.sftp.PacketReader.readPacket(PacketReader.java:76) ~[sshj-0.32.4.jar:?]
	at net.schmizz.sshj.sftp.SFTPEngine.init(SFTPEngine.java:91) ~[sshj-0.32.4.jar:?]


```

**Comment by dkocher** [comment]
Duplicate for #9334.

**Comment by tcurdt** [comment]
I guess the combination of 
https://github.com/MichaIng/DietPi/issues/3296
https://github.com/iterate-ch/cyberduck/issues/7712#issuecomment-980255324
explains it.

It would be fantastic to have a clearer error message.

**Comment by tcurdt** [comment]
`apt install openssh-sftp-server` solved this.

**Comment by lldb3** [comment]
For those using Fedora or variants: adding the `Subsystem       sftp    internal-sftp ` line to `/etc/ssh/sshd_config`, then restarting the sshd service will do the trick.
