### ISSUE TITLE
Its getting shuts after start

### ISSUE THREAD

**Issue by MY155** [iterate-ch/cyberduck#13337]
whenever I open cyberduck its open and get shuts automatically since last 4 days.

**Comment by AliveDevil** [comment]
Windows, macOS?
Please include debug information[^1] like logs and Crash Reports.

[^1]: https://docs.cyberduck.io/cyberduck/support/#logging-output

**Comment by dkocher** [comment]
```
Top-level Exception
Type:        java.util.NoSuchElementException
Message:     
Source:      IKVM.OpenJDK.Core
Stack Trace: at java.util.ArrayList.Itr.next()
   at ch.cyberduck.core.transfer.Transfer.getLocal()
   at Ch.Cyberduck.Ui.Controller.TransferController.<>c.<View_ValidateShowEvent>b__22_0(Transfer transfer)
   at Ch.Cyberduck.Ui.Controller.TransferController.ValidateToolbarItem(TransferToolbarValidator validate)
   at Ch.Cyberduck.Ui.Core.ValidateCommand.Invoke()
   at Ch.Cyberduck.Ui.Core.Commands.Command.Validate()
   at Ch.Cyberduck.Ui.Core.Commands.Validate()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Ch.Cyberduck.Ui.Program.Main(String[] args)
```
