### ISSUE TITLE
Unable to connect via SFTP

### ISSUE THREAD

**Issue by mathio** [iterate-ch/cyberduck#13442]
**Describe the bug**

Connecting via SFTP with password authentication fails. Cyberduck tries to authenticate via public key.
This is happening for Cyberduck version 8+. The issue is not present in Cyberduck 7.10.2.

**To Reproduce**
1. Create new SFTP connection bookmark
2. Setup authentication via password
3. Set SSH Private Key as "None"
4. Double click the bookmark to connect
5. The connection attempt is rejected, UI shows an error message:
> **Connection failed**
> Application error. The connection attempt was rejected. The server may be down, or your network may not be properly configured.

**Expected behavior**
Connection should not fail.
I was told by my hosting provider the client is trying to connect using public key however it is configured to use password instead. Cyberduck should authenticate using password.

**Screenshots**
![Screenshot 2022-06-08 at 00 31 11](https://user-images.githubusercontent.com/1561771/172494026-125661d0-948a-47d0-a3fc-f6af58cb5236.png)

**Desktop:**
 - OS: macOS Catalina 10.15.7
 - Version 8.3.3 (also tried with versions 8.2.3 and 8.0.0)

**Log Files**
*Note:* The domain was replaced with `example.com` in all logs.

Related Cyberduck log:
```
2022-06-08 00:16:40,223 [sshj-Reader-example.com/37.9.175.156:22] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
2022-06-08 00:16:40,244 [sshj-Reader-example.com/37.9.175.156:22] INFO  net.schmizz.sshj.transport.TransportImpl - Received SSH_MSG_DISCONNECT (reason=BY_APPLICATION, msg=Application error)
2022-06-08 00:16:40,244 [sshj-Reader-example.com/37.9.175.156:22] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Application error
net.schmizz.sshj.transport.TransportException: Application error
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:533) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:489) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[sshj-0.33.0.jar:?]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60) ~[sshj-0.33.0.jar:?]
```
Full log here: [cyberduck.log](https://github.com/iterate-ch/cyberduck/files/8856937/cyberduck.log)

Related log from hosting provider:
```
USER [example.com](http://example.com/) (Login failed): authentication via 'ssh-rsa' public key failed
```

**Additional context**
I can connect via `sftp` command line without any issues, therefore I can rule out general network issues.

**Workaround**
Downgrading all the way down to Cyberduck version 7.10.2 works fine.

**Comment by wtw** [comment]
I too am experiencing this issue. The log (on my side) does not add anything useful, I am getting „Too many authentication failures“ right now. Don't have any info from the server side.

**Additional context**
I can connect via ssh without any issues.

**Workaround**
For me 8.3.0, 8.3.1, 8.3.2 are working fine, 8.3.3 is showing said error. So the cause seems to be something [added in that version](https://github.com/iterate-ch/cyberduck/compare/release-8-3-2...release-8-3-3). Might relate to 63d1d6c?

**Comment by ylangisc** [comment]
@mathio Thanks for the logfile which does not give too much insight why the auth process fails. Any chance to post a logfile generated with version 7.10.2?

**Comment by wtw** [comment]
@ylangisc Debug log for `8.3.3` is attached, it should include everything around the failed attempt. I anonymized all sensitive data and removed about 400 lines of „`DEBUG net.schmizz.sshj.common.ECDSAVariationsAdapter - Key algo: ecdsa-sha2-nistp256, Key curve:`“ messages. Mind that this is a bookmark that works with version `8.3.2` without any changes, so the connection details are valid. Same problem persists in version `8.4.0`.

As @mathio mentioned there are failing authentication attempts with different keypairs. After these failing authentication attempts some background task returns null, which causes an exception. Authentication method `password` is never tried, only `none` and `publickey` are mentioned in the log. I compared the log briefly with the log from `8.3.2` and only in `8.3.3` I get this error:
`2022-06-28 15:36:14,545 [sshj-Reader-XXXSERVERNAMEXXX/XXXIPADDRESSXXX:22] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Too many authentication failures`, although the same SSH connection attempts should fail in `8.3.2` as well. Can it be that the code is not prepared for such an error and bails out before trying password authentication? Also the sshj dependency was updated between `8.3.2` (`0.32.4`) and `8.3.3` (`0.33.0`). Hope any of this guesswork helps. :)

[cyberduck-connection.log](https://github.com/iterate-ch/cyberduck/files/9002987/cyberduck-connection.log)

**Comment by ylangisc** [comment]
Thanks @wtw for the log. I can see that password auth would also be tried if all other options do not work but it looks like your server has set `MaxAuthTries` to 2 which makes the subsequent auth attempts fail. Any chance to also post a log of an auth attempt with version 8.3.2? Still not sure why the order of auth methods has changed.

**Comment by wtw** [comment]
Sure, it seems that the order of auth methods is the same, but not only two of my keys are used, but all four of them. There is no error after two attempts. It is the same bookmark/server and I can switch from 8.3.2 (works) to 8.3.3 (too many attempts) and back at will. After all keys failed, password auth is tried and succeeds.

[cyberduck-connection-8.3.2.log](https://github.com/iterate-ch/cyberduck/files/9008532/cyberduck-connection-8.3.2.log)

**Comment by vzz3** [comment]
I have the same Problem "Too many authentication failures. Please contact your web hosting service provider for assistance." with version 8.4.2 on MacOS 11.6 (20G165). After a downgrade to 8.3.2 it works as expected. Thanks to @wtw for posting the last working version numbers.

**Comment by asmaloney** [comment]
Just another "me too" - using a private key & no password on macOS 12.5.1.

It works if I use version 8.3.2 without changing anything else (thanks @wtw!)

I can ssh on the command line fine & I can access using FileZilla fine, but CyberDuck fails with "Too many authentication failures."

**Comment by ylangisc** [comment]
The latest snapshot version contains a fix for authentication with password.

**Comment by mathio** [comment]
Where can I find the latest snapshot please? The link on the website does not work (`https://docs.cyberduck.io/dirhtml/cyberduck/preferences/#Update`) and I could not find anything on Github. It is not fixed in latest stable release.

**Comment by wtw** [comment]
> Where can I find the latest snapshot please? The link on the website does not work (`https://docs.cyberduck.io/dirhtml/cyberduck/preferences/#Update`) and I could not find anything on Github. It is not fixed in latest stable release.

This issue seems to be fixed in version 8.4.4 (just upgraded and connects successfully): https://cyberduck.io/download/.

**Comment by AndreVirtimo** [comment]
I also can confirm that the bug is fixed with version 8.4.4.

**Comment by mathio** [comment]
I downloaded the 8.4.4 version. I kept it in `~/Downloads`, not to override the version 7 that is in `/Applications`. new version opened and displayed my bookmarks from version 7. I tried to connect but it failed. The error in log seems to be the same as in my first comment:

```
net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
2022-09-21 14:17:11,834 [sshj-Reader-example.com/37.9.175.156:22] INFO  net.schmizz.sshj.transport.TransportImpl - Received SSH_MSG_DISCONNECT (reason=BY_APPLICATION, msg=Application error)
2022-09-21 14:17:11,834 [sshj-Reader-example.com/37.9.175.156:22] ERROR net.schmizz.sshj.transport.TransportImpl - Dying because - Application error
net.schmizz.sshj.transport.TransportException: Application error
	at net.schmizz.sshj.transport.TransportImpl.gotDisconnect(TransportImpl.java:533) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.TransportImpl.handle(TransportImpl.java:489) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.decode(Decoder.java:113) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.Decoder.received(Decoder.java:200) ~[sshj-0.34.0.jar:?]
	at net.schmizz.sshj.transport.Reader.run(Reader.java:60) ~[sshj-0.34.0.jar:?]
2022-09-21 14:17:11,834 [sshj-Reader-example.com/37.9.175.156:22] WARN  ch.cyberduck.core.sftp.SFTPSession - Disconnected BY_APPLICATION
```
Full log: [cyberduck-8-4-4.log](https://github.com/iterate-ch/cyberduck/files/9616489/cyberduck-8-4-4.log)



When I connect with Cyberduck 7.10.2 it works.
```
2022-09-21 14:20:12,127 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Sending SSH_MSG_KEXDH_INIT
2022-09-21 14:20:12,141 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received kex followup data
2022-09-21 14:20:12,141 [reader] DEBUG net.schmizz.sshj.transport.kex.Curve25519SHA256 - Received SSH_MSG_KEXDH_REPLY
2022-09-21 14:20:12,154 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Trying to verify host key with ch.cyberduck.core.sftp.SFTPSession$1@313cda71
2022-09-21 14:20:12,159 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Sending SSH_MSG_NEWKEYS
2022-09-21 14:20:12,160 [reader] DEBUG net.schmizz.sshj.transport.KeyExchanger - Received SSH_MSG_NEWKEYS
2022-09-21 14:20:12,172 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<kexinit sent>> to `null`
2022-09-21 14:20:12,172 [reader] DEBUG net.schmizz.concurrent.Promise - Setting <<kex done>> to `SOME`
2022-09-21 14:20:12,172 [Thread-31] DEBUG net.schmizz.sshj.SSHClient - Key exchange took 0.06 seconds
2022-09-21 14:20:12,173 [Thread-31] DEBUG ch.cyberduck.core.Session - Connection did open to Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, port=22, hostname='example.com', credentials=Credentials{user='example.com', oauth='Tokens{accessToken='null', refreshToken='null'}', token='', identity=null}, uuid='2af3be97-f111-4b9d-b7b7-06e067b255fe', nickname='null', defaultpath='null', workdir=null, labels=[]}
```
Full log: [cyberduck-7-10-2.log](https://github.com/iterate-ch/cyberduck/files/9616499/cyberduck-7-10-2.log)

**Comment by wtw** [comment]
Might be a different error and/or root cause. Luckily, my issue got solved, so I can't provide more help or input here, sorry.

**Comment by Muutu** [comment]
We are encountering the same issue with 8.5.10 (39764). Cyberduck refuses to connect to our newest web hosting server. Works perfectly well with the older servers.

Server is running Ubuntu 22.04 with ProFTPD.

**Comment by ylangisc** [comment]
@Muutu This issue is closed. Refer to https://github.com/proftpd/proftpd/issues/1595.

**Comment by MrSimmo** [comment]
This is happening again with 9.1.0
