### ISSUE TITLE
Handle System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#13547]
```
Top-level Exception
Type:        System.UnauthorizedAccessException
Message:     Access to the path '%UserProfile%\.ssh\config' is denied.
Source:      mscorlib
Stack Trace: at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
  at System.IO.FileSystemInfo.get_Attributes()
  at sun.nio.fs.NetFileSystemProvider.DosFileAttributesViewImpl.readAttributesImpl(String )
  at sun.nio.fs.NetFileSystemProvider.readAttributes(Path , Class , LinkOption[] )
  at java.nio.file.Files.readAttributes(Path path, Class type, LinkOption[] options)
  at java.nio.file.Files.getLastModifiedTime(Path path, LinkOption[] options)
  at ch.cyberduck.core.LocalAttributes.getModificationDate()
  at ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig.refresh()
  at ch.cyberduck.core.sftp.openssh.config.transport.OpenSshConfig..ctor(Local configuration)
  at ch.cyberduck.core.sftp.openssh.OpenSSHCredentialsConfigurator..ctor()
  at ch.cyberduck.core.sftp.SFTPProtocol..ctor()
  at ch.iterate.mountainduck.windows.Controller.ProtocolController.Register()
  at ch.iterate.mountainduck.windows.App.OnStartup(StartupEventArgs e)
  at System.Windows.Application.<.ctor>b__1_0(Object unused)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.DispatcherOperation.InvokeImpl()
  at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
  at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
  at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
  at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
  at System.Windows.Threading.DispatcherOperation.Invoke()
  at System.Windows.Threading.Dispatcher.ProcessQueue()
  at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
  at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
  at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
  at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
  at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
  at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
  at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
  at System.Windows.Application.RunDispatcher(Object ignore)
  at System.Windows.Application.RunInternal(Window window)
  at ch.iterate.mountainduck.windows.App.Main()
  at ch.iterate.mountainduck.windows.Program.Main()
```

**Comment by AliveDevil** [comment]
Get Modification Date[^1] retrieval should be inside try.

**Comment by AliveDevil** [comment]
Need to debug IKVM in Debug-build. Dropping a profile from the list, as handled in ProtocolController is bad.

**Comment by AliveDevil** [comment]
Fixed with https://github.com/iterate-ch/ikvm/compare/8.0.312.b07-6...8.0.312.b07-7
Needs dependency update.
