### ISSUE TITLE
Connection profile not made available on profiles folder when checked in Preferences

### ISSUE THREAD

**Issue by eloyperezpousa** [iterate-ch/cyberduck#13739]
The cyberduck file for hubic is not made available on profiles folder when clicked on it

**Comment by helicofan** [comment]
Same problem when I try to transfert my data from Hubic to shadow drive
I use cyberduck on windows

**Comment by hevisko** [comment]
This is not limited to one, but all additional profiles for me :(

 #
```
om={}'}}}] from background action WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,453 [Thread-47] DEBUG ch.cyberduck.core.threading.AbstractBackgroundAction - Finish background task WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,453 [Thread-47] DEBUG ch.cyberduck.core.threading.BackgroundActionRegistry - Remove action WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,453 [Thread-47] DEBUG ch.cyberduck.core.threading.BackgroundActionRegistry - Remove action WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,453 [Thread-47] DEBUG ch.cyberduck.core.AbstractController - Stop action WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,453 [Thread-47] DEBUG ch.cyberduck.core.threading.BackgroundCallable - Invoke cleanup for background action WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,454 [Thread-47] DEBUG ch.cyberduck.core.threading.BackgroundCallable - Releasing lock for background runnable WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,454 [main] DEBUG ch.cyberduck.core.threading.WorkerBackgroundAction - Cleanup worker Worker{canceled=false}
2022-09-27 22:20:25,454 [Thread-47] DEBUG org.rococoa - Draining autorelease pool
2022-09-27 22:20:25,479 [main] DEBUG ch.cyberduck.core.threading.BackgroundActionRegistry - Remove action WorkerBackgroundAction{worker=Worker{canceled=false}}
2022-09-27 22:20:25,479 [main] INFO  ch.cyberduck.core.AbstractController - 
2022-09-27 22:20:25,479 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,481 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,481 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:25,481 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,482 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,483 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:25,483 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,484 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,484 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:25,484 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,485 [main] DEBUG ch.cyberduck.core.resources.NSImageIconCache - No cached image for /var/folders/rj/4dm5zr195kngf_swf6n1zvym0000gn/T/ch.sudo.cyberduck/8b8f64af-2fae-4344-8eaf-27275ff31f35/0pXJk0Sf
2022-09-27 22:20:25,486 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,486 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:25,487 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,488 [main] DEBUG ch.cyberduck.core.resources.NSImageIconCache - No cached image for /var/folders/rj/4dm5zr195kngf_swf6n1zvym0000gn/T/ch.sudo.cyberduck/9e46e1fd-bb36-4160-92ff-b93797150075/6zsPfYPk
2022-09-27 22:20:25,489 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,489 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:25,489 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,490 [main] DEBUG ch.cyberduck.core.resources.NSImageIconCache - No cached image for /var/folders/rj/4dm5zr195kngf_swf6n1zvym0000gn/T/ch.sudo.cyberduck/cd3ad94a-9f93-4975-b5e4-651435fa711f/6vYB1SV9
2022-09-27 22:20:25,491 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,491 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:25,491 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,492 [main] DEBUG ch.cyberduck.core.resources.NSImageIconCache - No cached image for /var/folders/rj/4dm5zr195kngf_swf6n1zvym0000gn/T/ch.sudo.cyberduck/c667d28a-a5fb-4883-92bf-e7a1efde9754/PKsElkc1
2022-09-27 22:20:25,493 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,493 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:25,494 [main] INFO  ch.cyberduck.binding.BundleController - Loading bundle Profile
2022-09-27 22:20:25,494 [main] DEBUG ch.cyberduck.core.resources.NSImageIconCache - No cached image for /var/folders/rj/4dm5zr195kngf_swf6n1zvym0000gn/T/ch.sudo.cyberduck/10d766ec-955d-4707-ab30-866673f7ec0f/2NHgVOxl
2022-09-27 22:20:25,495 [main] DEBUG ch.cyberduck.binding.BundleController - awakeFromNib
2022-09-27 22:20:25,495 [main] DEBUG org.rococoa.callback - No method outlineView_didAddRowView_forRow for selector:outlineView:didAddRowView:forRow:
2022-09-27 22:20:30,047 [main] ERROR ch.cyberduck.core.ProtocolFactory - Failure BackgroundException{class=class ch.cyberduck.core.exception.LocalAccessDeniedException, file=null, message='Access denied', detail='/var/folders/rj/4dm5zr195kngf_swf6n1zvym0000gn/T/ch.sudo.cyberduck/5ac5fc23-1f56-4375-b361-7d378a2ffc9d/AWS PrivateLink for Amazon S3 (VPC endpoint).cyberduckprofile', cause='null'} reading profile Local{path='/var/folders/rj/4dm5zr195kngf_swf6n1zvym0000gn/T/ch.sudo.cyberduck/5ac5fc23-1f56-4375-b361-7d378a2ffc9d/AWS PrivateLink for Amazon S3 (VPC endpoint).cyberduckprofile'}
2022-09-27 22:20:30,048 [main] ERROR org.rococoa.callback - Exception calling method for selector profileCheckboxClicked:
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:315) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at org.rococoa.internal.MsgSendHandler.invoke(MsgSendHandler.java:114) ~[rococoa-core-0.9.1.jar:?]
	at com.sun.jna.Library$Handler.invoke(Library.java:263) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at jdk.proxy2.$Proxy5.syntheticSendMessage(Unknown Source) ~[?:?]
	at org.rococoa.Foundation.send(Foundation.java:207) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.Foundation.send(Foundation.java:181) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.sendOnThisOrMainThread(ObjCObjectInvocationHandler.java:245) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.invokeCocoa(ObjCObjectInvocationHandler.java:212) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.intercept(ObjCObjectInvocationHandler.java:171) ~[rococoa-core-0.9.1.jar:?]
	at ch.cyberduck.binding.application.NSApplication$$ByRococoa.run(<generated>) ~[binding-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at ch.cyberduck.ui.cocoa.MainApplication.main(MainApplication.java:122) ~[osx-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
Caused by: java.lang.NullPointerException: Cannot invoke "ch.cyberduck.core.Local.getInputStream()" because "this.val$file" is null
	at ch.cyberduck.core.profiles.LocalProfileDescription$1.initialize(LocalProfileDescription.java:56) ~[core-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at ch.cyberduck.core.profiles.LocalProfileDescription$1.initialize(LocalProfileDescription.java:51) ~[core-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:106) ~[commons-lang3-3.12.0.jar:3.12.0]
	at ch.cyberduck.core.profiles.ProfileDescription.hashCode(ProfileDescription.java:139) ~[core-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at java.util.HashMap.hash(Unknown Source) ~[?:?]
	at java.util.HashMap.put(Unknown Source) ~[?:?]
	at java.util.Collections$SynchronizedMap.put(Unknown Source) ~[?:?]
	at ch.cyberduck.ui.cocoa.controller.ProfilesPreferencesController$ProfileTableViewController.lambda$profileCheckboxClicked$1(ProfilesPreferencesController.java:445) ~[osx-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at ch.cyberduck.ui.cocoa.controller.ProfilesPreferencesController$ProfileTableViewController.profileCheckboxClicked(ProfilesPreferencesController.java:445) ~[osx-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	... 26 more
2022-09-27 22:20:30,049 [main] WARN  com.sun.jna.Native - JNA: Callback org.rococoa.internal.OCInvocationCallbacks$2@52454457 threw the following exception
org.rococoa.RococoaException: Exception calling method for selector profileCheckboxClicked:
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:174) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor78.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:315) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at org.rococoa.internal.MsgSendHandler.invoke(MsgSendHandler.java:114) ~[rococoa-core-0.9.1.jar:?]
	at com.sun.jna.Library$Handler.invoke(Library.java:263) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at jdk.proxy2.$Proxy5.syntheticSendMessage(Unknown Source) ~[?:?]
	at org.rococoa.Foundation.send(Foundation.java:207) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.Foundation.send(Foundation.java:181) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.sendOnThisOrMainThread(ObjCObjectInvocationHandler.java:245) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.invokeCocoa(ObjCObjectInvocationHandler.java:212) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.intercept(ObjCObjectInvocationHandler.java:171) ~[rococoa-core-0.9.1.jar:?]
	at ch.cyberduck.binding.application.NSApplication$$ByRococoa.run(<generated>) ~[binding-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at ch.cyberduck.ui.cocoa.MainApplication.main(MainApplication.java:122) ~[osx-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
Caused by: java.lang.NullPointerException: Cannot invoke "ch.cyberduck.core.Local.getInputStream()" because "this.val$file" is null
	at ch.cyberduck.core.profiles.LocalProfileDescription$1.initialize(LocalProfileDescription.java:56) ~[core-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at ch.cyberduck.core.profiles.LocalProfileDescription$1.initialize(LocalProfileDescription.java:51) ~[core-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at org.apache.commons.lang3.concurrent.LazyInitializer.get(LazyInitializer.java:106) ~[commons-lang3-3.12.0.jar:3.12.0]
	at ch.cyberduck.core.profiles.ProfileDescription.hashCode(ProfileDescription.java:139) ~[core-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at java.util.HashMap.hash(Unknown Source) ~[?:?]
	at java.util.HashMap.put(Unknown Source) ~[?:?]
	at java.util.Collections$SynchronizedMap.put(Unknown Source) ~[?:?]
	at ch.cyberduck.ui.cocoa.controller.ProfilesPreferencesController$ProfileTableViewController.lambda$profileCheckboxClicked$1(ProfilesPreferencesController.java:445) ~[osx-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at ch.cyberduck.ui.cocoa.controller.ProfilesPreferencesController$ProfileTableViewController.profileCheckboxClicked(ProfilesPreferencesController.java:445) ~[osx-8.4.4.jar:89bf82c9d89b6451e87aab370c46cd2b7b19766a]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) ~[rococoa-core-0.9.1.jar:?]
	... 21 more
2022-09-27 22:20:31,691 [main] DEBUG ch.cyberduck.binding.application.NSApplication - NSConcreteNotification 0x600003b6bc00 {name = NSApplicationWillResignActiveNotification; object = <NSApplication: 0x142222310>}
2022-09-27 22:20:31,696 [main] DEBUG ch.cyberduck.binding.WindowController - Resign key for window <NSPanel: 0x13074c920>
2022-09-27 22:20:31,696 [main] DEBUG ch.cyberduck.binding.WindowController - Resign main for window <NSWindow: 0x1421909d0>
2022-09-27 22:20:31,700 [main] DEBUG ch.cyberduck.binding.application.NSApplication - NSConcreteNotification 0x600003b56740 {name = NSApplicationDidResignActiveNotification; object = <NSApplication: 0x142222310>}
2022-09-27 22:20:31,709 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:31,809 [main] DEBUG org.rococoa.callback - No method applicationSupportsSecureRestorableState for selector:applicationSupportsSecureRestorableState:
2022-09-27 22:20:37,329 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,345 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,355 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,357 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,359 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,360 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,361 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,363 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,364 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,365 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,366 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,367 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,368 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:37,370 [main] WARN  ch.cyberduck.binding.BundleController - Bundle Profiles already loaded
2022-09-27 22:20:55,247 [Finalizer] DEBUG org.rococoa - Draining autorelease pool
```

**Comment by dkocher** [comment]
Regression from 5a2ec301.

**Comment by tatze96** [comment]
As a workaround download the connection profile from our [wiki page](https://docs.cyberduck.io/protocols/) and copy it into the *Profiles* folder within the application support folder. Make sure that Cyberduck isn't running while doing that.

To reach the application support folder
- on **macOS**, choose `Go → Go to folder` within the *Finder* menu, copy the path below into the appearing window, and click on the *Open* button afterward.
```
~/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/
```
- on **Windows**, copy the path below into the address bar of Windows Explorer and press Return afterward.
```
%AppData%\Cyberduck
```

The connection profile should appear within the list of protocols after you start Cyberduck again.

**Comment by Phillbaska** [comment]
> As a workaround download the connection profile from our [wiki page](https://docs.cyberduck.io/protocols/) and copy it into the _Profiles_ folder within the application support folder. Make sure that Cyberduck isn't running while doing that.
> 
> To reach the application support folder
> 
> * on **macOS**, choose `Go → Go to folder` within the _Finder_ menu, copy the path below into the appearing window, and click on the _Open_ button afterward.
> 
> ```
> ~/Library/Group Containers/G69SCX94XU.duck/Library/Application Support/duck/
> ```
> 
> * on **Windows**, copy the path below into the address bar of Windows Explorer and press Return afterward.
> 
> ```
> %AppData%\Cyberduck
> ```
> 
> The connection profile should appear within the list of protocols after you start Cyberduck again.

Hello, i'm trying to use the work around method, but i can't seem to find the linode object storage connection profile on the wiki?

![Screenshot 2022-09-30 at 07 26 18](https://user-images.githubusercontent.com/81318169/193196572-909ce4d6-48a0-42c7-92ab-480f14936a8a.png)
(the profile i would like)

**Comment by Phillbaska** [comment]
As a work around i've just downloaded an older version for now which works:

[8.4.1](https://trac.cyberduck.io/milestone/8.4.1) 29 Jun 2022
https://cyberduck.io/changelog/

**Comment by hvisage** [comment]
> Regression from [5a2ec30](https://github.com/iterate-ch/cyberduck/commit/5a2ec3019ca74b2b42137e338f46fcd0116f5cfb).

This also affected MountainDuck. is the fix fixing it there too?

**Comment by dkocher** [comment]
> > Regression from [5a2ec30](https://github.com/iterate-ch/cyberduck/commit/5a2ec3019ca74b2b42137e338f46fcd0116f5cfb).
> 
> This also affected MountainDuck. is the fix fixing it there too?

Yes, the fix will apply to Mountain Duck as well.

**Comment by dkocher** [comment]
Please try the [snapshot build](https://docs.cyberduck.io/cyberduck/faq/#snapshot-and-beta-builds) 8.4.5.38394 or later.

**Comment by markabur** [comment]
I've seen this same issue with 8.7.1 (Mac app store version). Eventually it showed up though. Maybe after I quit and relaunched?

**Comment by dkocher** [comment]
> I've seen this same issue with 8.7.1 (Mac app store version). Eventually it showed up though. Maybe after I quit and relaunched?

Possibly just a problem with refreshing folder contents in Finder.app
