### ISSUE TITLE
Actualización v8.4.X

### ISSUE THREAD

**Issue by jaimeontiveros** [iterate-ch/cyberduck#13768]
Despues de actualizar a la version 8.4.X se me ha presentado el cierre inesperado de la aplicación, 
normalmente se da al intentar editar algún archivo, anteriormente funcionaba sin complicaciones

**Comment by AliveDevil** [comment]
> After upgrading to version 8.4.X I have had an unexpected application shutdown, usually occurs when trying to edit a file, previously it worked without complications.

Please attach all relevant debug log files[^debug], system information, and used editing application (name) in a comment.
[^debug]: https://docs.cyberduck.io/cyberduck/support/#logging-output

**Comment by jaimeontiveros** [comment]
[background-3] ERROR AsyncController - Unhandled exception during invoke
cli.System.Runtime.InteropServices.COMException: No se pudo recuperar el generador de clases COM para el componente con CLSID {AA509086-5CA9-4C25-8F95-589D3C07B48A} debido al siguiente error: 80040154 Clase no registrada (Excepción de HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
	at cli.System.Windows.Forms.Control.MarshaledInvoke(Unknown Source) ~[System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Control.Invoke(Unknown Source) ~[System.Windows.Forms.dll:?]
	at cli.Ch.Cyberduck.Ui.Controller.AsyncController.invoke(Unknown Source) ~[Cyberduck.exe:?]
	at java.lang.Throwable.getLocalizedMessage(map.xml:1230) ~[?:1.8.0]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:108) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:98) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:347) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:383) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:216) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:302) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:136) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:90) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:682) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:626) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:162) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2018) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1985) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:751) ~[Cyberduck.Core.DLL:2.19.0]
	at cli.Ch.Cyberduck.Ui.Controller.AsyncController.invoke(Unknown Source) ~[Cyberduck.exe:?]
	at cli.Ch.Cyberduck.Ui.Controller.WindowController.invoke(Unknown Source) ~[Cyberduck.exe:?]
	at cli.Ch.Cyberduck.Ui.Controller.MainController.<InitializeSessions>b__55_3(Unknown Source) ~[Cyberduck.exe:?]
	at ch.cyberduck.core.threading.BackgroundCallable$1.run(BackgroundCallable.java:75) ~[Cyberduck.Core.DLL:a21ad8ceb1088b1240ab2dd55aa9e5295c494d51]
	at ch.cyberduck.core.AbstractController.invoke(AbstractController.java:49) ~[Cyberduck.Core.DLL:a21ad8ceb1088b1240ab2dd55aa9e5295c494d51]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:46) ~[Cyberduck.Core.DLL:a21ad8ceb1088b1240ab2dd55aa9e5295c494d51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:625) ~[?:1.8.0]
	at ch.cyberduck.core.threading.NamedThreadFactory$1.run(NamedThreadFactory.java:59) ~[Cyberduck.Core.DLL:a21ad8ceb1088b1240ab2dd55aa9e5295c494d51]
	at java.lang.Thread.run(Thread.java:955) ~[?:1.8.0]

**Windows 7 Professional

Cyberduck Version 8.4.5 (38394)**

**Comment by AliveDevil** [comment]
Cyberduck 8.4 requires Windows 10 (2016) or later.
Please downgrade to the latest 8.3.3 release from the [changelog](https://cyberduck.io/changelog/).

**Comment by jaimeontiveros** [comment]
Gracias, se ha solucionado al bajar de versión
