### ISSUE TITLE
Failure parsing date when reading SSO credentials from cache file of AWS CLI

### ISSUE THREAD

**Issue by manelizzard** [iterate-ch/cyberduck#14177]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
Trying to connect with AWS SSO but Cyberduck logs show a `DateTimeParseException` while paring expiration date from .aws/sso/cache

**To Reproduce**
1. Go to 'New connection'
2. Select "AWS S3 (Credentials from AWS Command Line Interface)"
3. Make sure aws sso is properly setup
4. Connect in Cyberduc
4. Go to cyberduck.log and check the DateTimeParseException

**Expected behavior**
The connection succeeds

**Screenshots**

`2023-02-03 11:07:28,257 [Thread-142] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure java.time.format.DateTimeParseException: Text '2023-02-03T22:03:19UTC' could not be parsed at index 19 running background task
java.lang.Exception: null
	at ch.cyberduck.core.threading.BackgroundCallable.<init>(BackgroundCallable.java:37) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.DefaultBackgroundExecutor.execute(DefaultBackgroundExecutor.java:81) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.AbstractController.background(AbstractController.java:72) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$33.run(BrowserController.java:3271) ~[osx-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$36.run(BrowserController.java:3398) ~[osx-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$37.cleanup(BrowserController.java:3417) ~[osx-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.BackgroundCallable$1.run(BackgroundCallable.java:75) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at org.rococoa.internal.MainThreadUtils$3.callback(MainThreadUtils.java:91) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:315) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at org.rococoa.internal.MsgSendHandler.invoke(MsgSendHandler.java:114) ~[rococoa-core-0.9.1.jar:?]
	at com.sun.jna.Library$Handler.invoke(Library.java:263) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at jdk.proxy2.$Proxy5.syntheticSendMessage(Unknown Source) ~[?:?]
	at org.rococoa.Foundation.send(Foundation.java:207) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.Foundation.send(Foundation.java:181) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.sendOnThisOrMainThread(ObjCObjectInvocationHandler.java:245) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.invokeCocoa(ObjCObjectInvocationHandler.java:212) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.intercept(ObjCObjectInvocationHandler.java:171) ~[rococoa-core-0.9.1.jar:?]
	at ch.cyberduck.binding.application.NSApplication$$ByRococoa.run(<generated>) ~[binding-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.ui.cocoa.MainApplication.main(MainApplication.java:122) ~[osx-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
Caused by: java.time.format.DateTimeParseException: Text '2023-02-03T22:03:19UTC' could not be parsed at index 19
	at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source) ~[?:?]
	at java.time.format.DateTimeFormatter.parse(Unknown Source) ~[?:?]
	at java.time.Instant.parse(Unknown Source) ~[?:?]
	at ch.cyberduck.core.sts.STSCredentialsConfigurator.fetchSsoCredentials(STSCredentialsConfigurator.java:321) ~[s3-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.sts.STSCredentialsConfigurator.configure(STSCredentialsConfigurator.java:233) ~[s3-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.s3.S3Session.login(S3Session.java:185) ~[s3-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.KeychainLoginService.authenticate(KeychainLoginService.java:192) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.LoginConnectionService.authenticate(LoginConnectionService.java:166) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.LoginConnectionService.connect(LoginConnectionService.java:157) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.LoginConnectionService.check(LoginConnectionService.java:100) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.pool.StatelessSessionPool.borrow(StatelessSessionPool.java:56) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.SessionBackgroundAction.run(SessionBackgroundAction.java:119) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.SessionBackgroundAction$1.call(SessionBackgroundAction.java:107) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.DefaultRetryCallable.call(DefaultRetryCallable.java:52) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.SessionBackgroundAction.call(SessionBackgroundAction.java:109) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.BackgroundCallable.run(BackgroundCallable.java:95) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:59) ~[core-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at ch.cyberduck.core.threading.DispatchExecutorService$InvocationFutureTask.run(DispatchExecutorService.java:281) ~[libcore-8.5.5.jar:1f62ed6384696a39a9c3b22c7d3a71054c9ba87c]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]`

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 8.5.5

**Log Files**
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/10577886/cyberduck.log)

**Additional context**

**Comment by yuzawa-san** [comment]
What version of the aws-cli are you using? the date format was broken in [some older versions](https://github.com/aws/aws-sdk-java-v2/issues/2190), so try upgrading the cli and it should work.

**Comment by manelizzard** [comment]
Issue happening with:

```
aws --version
aws-cli/2.0.8 Python/3.7.4 Darwin/22.1.0 botocore/2.0.0dev12
```

After updating aws:

```
aws --version
aws-cli/2.10.1 Python/3.9.11 Darwin/22.1.0 exe/x86_64 prompt/off
```

🟢 **Now it works**. Thank you for the suggestion @yuzawa-san
