### ISSUE TITLE
Clarify error message: cli.System.UriFormatException: Invalid URI: The hostname could not be parsed

### ISSUE THREAD

**Issue by minfrin** [iterate-ch/cyberduck#14198]
**Describe the bug**
Mountain duck logs a message about being unable to parse the hostname of an unspecified URL.

Without logging what the URL is that it is unable to parse, there is no way to troubleshoot this, or see that this message is relevant to a different problem.

**To Reproduce**
1. Enable debug log.
2. View log.

**Expected behavior**
An error message saying "Invalid URI: The hostname could not be parsed", along with the URL that cannot be parsed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Unknown

**Log Files**
```
2023-01-24 14:47:40,762 [Thread-7] ERROR Ch.Cyberduck.Core.Diagnostics.TcpReachability - Generic exception while checking for reachability for {h}
cli.System.UriFormatException: Invalid URI: The hostname could not be parsed.
	at cli.System.Uri.CreateThis(Unknown Source) ~[System.dll:?]
	at cli.System.Net.WebRequest.CreateHttp(Unknown Source) ~[System.dll:?]
	at cli.Ch.Cyberduck.Core.Diagnostics.TcpReachability.isReachable(Unknown Source) ~[Cyberduck.Core.Native.DLL:?]
	at java.lang.Throwable.getLocalizedMessage(map.xml:1230) ~[?:1.8.0]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:108) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:98) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:347) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:383) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:216) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:302) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:136) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:90) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:682) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:626) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:162) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2018) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1985) ~[Cyberduck.Core.DLL:2.19.0]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:751) ~[Cyberduck.Core.DLL:2.19.0]
	at cli.Ch.Cyberduck.Core.Diagnostics.TcpReachability.isReachable(Unknown Source) ~[Cyberduck.Core.Native.DLL:?]
```

**Additional context**

It looks like there is an attempt to include the hostname in the form {h}, but the parameter containing the hostname is not included.

Ideally the URL needs to be included, in case the hostname is something like "".

**Comment by AliveDevil** [comment]
You can check for `Reachability test with url`, which URL is tested.

**Comment by minfrin** [comment]
> You can check for `Reachability test with url`, which URL is tested.

Without a URL being logged, there is no way to know where this came from. The end user is complaining of a certificate verification failure, which looks like a different problem to this one, but no way to be sure.
