### ISSUE TITLE
COMException 0x80070490 SHLoadIndirectString

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#14331]
```
Top-level Exception
Type:        System.Runtime.InteropServices.COMException
Message:     Element nicht gefunden. (Ausnahme von HRESULT: 0x80070490)
Source:      mscorlib
Stack Trace: bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei Windows.Win32.CorePInvoke.SHLoadIndirectString(PCWSTR pszSource)
   bei Ch.Cyberduck.Core.Refresh.Services.IconProvider`1.GetApplication(Application application, Int32 size)
   bei Ch.Cyberduck.Ui.Winforms.BrowserForm.OnEditMenuItemPopup(Object sender, EventArgs e)
   bei System.Windows.Forms.MenuItem.OnPopup(EventArgs e)
   bei System.Windows.Forms.Menu.ProcessInitMenuPopup(IntPtr handle)
   bei System.Windows.Forms.Control.WmInitMenuPopup(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei BrightIdeasSoftware.ObjectListView.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

```
Top-level Exception
Type:        System.Runtime.InteropServices.COMException
Message:     Element nicht gefunden. (Ausnahme von HRESULT: 0x80070490)
Source:      mscorlib
Stack Trace: bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei Windows.Win32.CorePInvoke.SHLoadIndirectString(PCWSTR pszSource)
   bei Ch.Cyberduck.Core.Refresh.Services.IconProvider`1.GetApplication(Application application, Int32 size)
   bei Ch.Cyberduck.Ui.Winforms.BrowserForm.OnEditMenuItemPopup(Object sender, EventArgs e)
   bei System.Windows.Forms.MenuItem.OnPopup(EventArgs e)
   bei System.Windows.Forms.Menu.ProcessInitMenuPopup(IntPtr handle)
   bei System.Windows.Forms.Form.WmInitMenuPopup(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

```
Top-level Exception
Type:        System.Runtime.InteropServices.COMException
Message:     Element nicht gefunden. (Ausnahme von HRESULT: 0x80070490)
Source:      mscorlib
Stack Trace: bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bei Windows.Win32.CorePInvoke.SHLoadIndirectString(PCWSTR pszSource)
   bei Ch.Cyberduck.Core.Refresh.Services.IconProvider`1.GetApplication(Application application, Int32 size)
   bei Ch.Cyberduck.Ui.Winforms.BrowserForm.OnEditorActionMenuOpening(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
   bei System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
   bei System.Windows.Forms.ToolStripDropDown.Show()
   bei System.Windows.Forms.ToolStripDropDownItem.ShowDropDownInternal()
   bei System.Windows.Forms.ToolStripSplitButton.OnMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseDown(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseDown(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei Ch.Cyberduck.Ui.Winforms.Controls.ClickThroughToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by AliveDevil** [comment]
```
2023-03-09 13:33:33,087 [Thread-0] DEBUG ch.cyberduck.core.editor.EditorFactory - Find installed editors for file IMG_6530.jpg
2023-03-09 13:33:33,227 [Thread-0] ERROR cli.System.Drawing.Image - Failure extracting icon for microsoft winrt storage-api. Icon path: @{Microsoft.MSPaint_1.0.21.0_x64__8wekyb3d8bbwe?ms-resource://Microsoft.MSPaint/Files/Assets/Logos/Square44x44/PaintAppList.png} (Index: 0, Indirect: "@{Microsoft.MSPaint_1.0.21.0_x64__8wekyb3d8bbwe?ms-resource://Microsoft.MSPaint/Files/Assets/Logos/Square44x44/PaintAppList.png}")
cli.System.Runtime.InteropServices.COMException: Element nicht gefunden. (Ausnahme von HRESULT: 0x80070490)
	at cli.System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Unknown Source) ~[mscorlib.dll:?]
	at cli.System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Unknown Source) ~[mscorlib.dll:?]
	at cli.Windows.Win32.Foundation.HRESULT.ThrowOnFailure(Unknown Source) ~[Cyberduck.Core.Native.DLL:?]
	at cli.Windows.Win32.CorePInvoke.SHLoadIndirectString(Unknown Source) ~[Cyberduck.Core.Native.DLL:?]
	at cli.Ch.Cyberduck.Core.Refresh.Services.IconProvider$$00601.GetApplication(Unknown Source) ~[Cyberduck.Core.Refresh.DLL:?]
	at java.lang.Throwable.getLocalizedMessage(map.xml:1230) ~[?:1.8.0]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:110) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:97) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:354) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:384) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:215) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:683) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:641) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:624) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.core.Logger.log(Logger.java:163) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2168) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2122) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2105) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1980) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1946) [Cyberduck.Core.DLL:2.20.0]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:718) [Cyberduck.Core.DLL:2.20.0]
	at cli.Ch.Cyberduck.Core.Refresh.Services.IconProvider$$00601.GetApplication(Unknown Source) [Cyberduck.Core.Refresh.DLL:?]
	at cli.Ch.Cyberduck.Ui.Winforms.BrowserForm.OnEditMenuItemPopup(Unknown Source) [Cyberduck.exe:?]
	at cli.System.Windows.Forms.MenuItem.OnPopup(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Menu.ProcessInitMenuPopup(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Control.WmInitMenuPopup(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Control.WndProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.ListView.WndProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.BrightIdeasSoftware.ObjectListView.WndProc(Unknown Source) [ObjectListView.DLL:?]
	at cli.System.Windows.Forms.NativeWindow.Callback(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.SafeNativeMethods.TrackPopupMenuEx(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.SafeNativeMethods.TrackPopupMenuEx(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.ContextMenu.Show(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Control.WmContextMenu(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Control.WndProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.ListView.WndProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.NativeWindow.Callback(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.UnsafeNativeMethods.CallWindowProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.NativeWindow.DefWndProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.ListView.WmMouseDown(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.ListView.WndProc(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.NativeWindow.Callback(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Application$ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoopInner(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoop(Unknown Source) [System.Windows.Forms.dll:?]
	at cli.Ch.Cyberduck.Ui.Program.Main(Unknown Source) [Cyberduck.exe:?]
```

WTF!?

(╯‵□′)╯︵┻━┻
