### ISSUE TITLE
Broken transport; encountered EOF with recent sshj lib and newer versions of Cyberduck past 8.1.1

### ISSUE THREAD

**Issue by basejump** [iterate-ch/cyberduck#14990]
**Describe the bug**
Connecting to a certain sites works with version `Version 8.1.1 (36550)` which I think uses  0.32.0. Connection fails with an version of Cyberduck after that. latest Cyberduck version looks like it uses newer sshj lib `0.34.0`. 

We use sshj in our app as well and logged this issue https://github.com/hierynomus/sshj/issues/886
our resolution is at the bottom to resolve the connection issues with the newer version after 0.32

error
```
Exhausted available authentication methods
net.schmizz.sshj.userauth.UserAuthException: Exhausted available authentication methods
	at app//net.schmizz.sshj.SSHClient.auth(SSHClient.java:230)
	at app//net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:345)
	at app//net.schmizz.sshj.SSHClient.authPublickey(SSHClient.java:393)
	at app//yakworks.ssh.SftpUtils.getSshClient(SftpUtils.groovy:40)
	at app//nine.banks.sftp.WellsFargoSftpSmokeTest.getSession(WellsFargoSftpSmokeTest.groovy:39)
	at app//nine.banks.sftp.WellsFargoSftpSmokeTest.setup(WellsFargoSftpSmokeTest.groovy:44)
Caused by: net.schmizz.sshj.userauth.UserAuthException: Broken transport; encountered EOF
	at app//net.schmizz.sshj.userauth.UserAuthException$1.chain(UserAuthException.java:33)
	at app//net.schmizz.sshj.userauth.UserAuthException$1.chain(UserAuthException.java:26)
	at app//net.schmizz.concurrent.Promise.deliverError(Promise.java:95)
	at app//net.schmizz.sshj.userauth.UserAuthImpl.notifyError(UserAuthImpl.java:157)
	at app//net.schmizz.sshj.transport.TransportImpl.die(TransportImpl.java:598)
	at app//net.schmizz.sshj.transport.Reader.run(Reader.java:66)
```

The fix that worked for use based on his feedback https://github.com/hierynomus/sshj/issues/886#issuecomment-1669867481
 
```
DefaultConfig config = new DefaultConfig();
config.prioritizeSshRsaKeyAlgorithm();
SSHClient ssh = new SSHClient(config);
```

**Comment by dkocher** [comment]
Relates to #12733. You will have to limit the authentication attempts or increase the limit on the server. Refer to our [documentation](https://docs.cyberduck.io/protocols/sftp/#too-many-authentication-failures).

**Comment by dkocher** [comment]
Duplicate for #13675.
