### ISSUE TITLE
Cyberduck keeps disconnecting

### ISSUE THREAD

**Issue by andrastudio** [iterate-ch/cyberduck#15090]
I know there are already some report about this bug but I can't comment on the issue because there are closed for new comment.

I'm still experiencing my Cyberduck keeps on disconnecting after being idle for a few seconds, I need to keep doing something on Cyberduck in order for it not disconnecting. It's been happening since several years ago, even after I upgraded to a new Macbook the issue remains.

I'm currently using Cyberduck 8.6.3 (40040) on Macbook Pro M1 running on MacOS Ventura.

Here's the log:

2023-09-06 08:37:08,347 [Thread-7049] WARN  ch.cyberduck.core.pool.StatelessSessionPool - Keep connection Session{host=Host{protocol=Profile{parent=sftp, vendor=iterate GmbH, description=null, image=null}, region='null', port=22, hostname='xxx.xxx.xxx.xxx', credentials=Credentials{user='user', oauth='OAuthTokens{accessToken='', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=null}, uuid='c268897a-9a03-4573-9b66-d3fc132bda7e', nickname='MySERVER', defaultpath='/home/user/webapps', workdir=null, custom=null, labels=null}, state=open} alive with failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=Path{path='/home/user/webapps/themainpop/wp-content/themes/themainpop', type=[directory]}, message='Listing directory themainpop failed.', detail='Timeout expired: 15000 MILLISECONDS.', cause='net.schmizz.sshj.sftp.SFTPException: Timeout expired: 15000 MILLISECONDS'}
2023-09-06 08:37:08,349 [Thread-7049] WARN  ch.cyberduck.core.threading.AbstractRetryCallable - Cancel retry for failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=Path{path='/home/user/webapps/themainpop/wp-content/themes/themainpop', type=[directory]}, message='Listing directory themainpop failed.', detail='Timeout expired: 15000 MILLISECONDS.', cause='net.schmizz.sshj.sftp.SFTPException: Timeout expired: 15000 MILLISECONDS'} after 1 counts
2023-09-06 08:37:08,349 [Thread-7049] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure running background task WorkerBackgroundAction{worker=SessionListWorker{directory=Path{path='/home/user/webapps/themainpop/wp-content/themes/themainpop', type=[directory]}}}
java.lang.Exception: null
	at ch.cyberduck.core.threading.BackgroundCallable.<init>(BackgroundCallable.java:38) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.DefaultBackgroundExecutor.execute(DefaultBackgroundExecutor.java:81) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.AbstractController.background(AbstractController.java:72) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.reload(BrowserController.java:527) ~[osx-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.reloadButtonClicked(BrowserController.java:2268) ~[osx-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) [rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor4730.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) [jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) [jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:315) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at org.rococoa.internal.MsgSendHandler.invoke(MsgSendHandler.java:114) ~[rococoa-core-0.9.1.jar:?]
	at com.sun.jna.Library$Handler.invoke(Library.java:263) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at jdk.proxy2.$Proxy5.syntheticSendMessage(Unknown Source) ~[?:?]
	at org.rococoa.Foundation.send(Foundation.java:207) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.Foundation.send(Foundation.java:181) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.sendOnThisOrMainThread(ObjCObjectInvocationHandler.java:245) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.invokeCocoa(ObjCObjectInvocationHandler.java:212) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.intercept(ObjCObjectInvocationHandler.java:171) ~[rococoa-core-0.9.1.jar:?]
	at ch.cyberduck.binding.application.NSApplication$$ByRococoa.run(<generated>) ~[binding-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.ui.cocoa.MainApplication.main(MainApplication.java:124) ~[osx-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
Caused by: ch.cyberduck.core.exception.InteroperabilityException: Listing directory themainpop failed.
	at ch.cyberduck.core.sftp.SFTPExceptionMappingService.map(SFTPExceptionMappingService.java:90) ~[ssh-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.sftp.SFTPExceptionMappingService.map(SFTPExceptionMappingService.java:50) ~[ssh-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.AbstractExceptionMappingService.map(AbstractExceptionMappingService.java:53) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.sftp.SFTPListService.list(SFTPListService.java:96) ~[ssh-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.vault.VaultFinderListService.list(VaultFinderListService.java:46) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.vault.registry.VaultRegistryListService.list(VaultRegistryListService.java:68) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:62) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:37) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.WorkerBackgroundAction.run(WorkerBackgroundAction.java:70) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction.run(SessionBackgroundAction.java:122) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction$1.call(SessionBackgroundAction.java:106) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.DefaultRetryCallable.call(DefaultRetryCallable.java:52) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction.call(SessionBackgroundAction.java:108) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.BackgroundCallable.run(BackgroundCallable.java:96) [core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:60) [core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at ch.cyberduck.core.threading.DispatchExecutorService$InvocationFutureTask.run(DispatchExecutorService.java:281) [libcore-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
Caused by: net.schmizz.sshj.sftp.SFTPException: Timeout expired: 15000 MILLISECONDS
	at net.schmizz.sshj.sftp.SFTPException$1.chain(SFTPException.java:33) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.sftp.SFTPException$1.chain(SFTPException.java:26) ~[sshj-0.35.0.jar:?]
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:146) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.sftp.SFTPEngine.openDir(SFTPEngine.java:169) ~[sshj-0.35.0.jar:?]
	at ch.cyberduck.core.sftp.SFTPListService.list(SFTPListService.java:61) ~[ssh-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.vault.VaultFinderListService.list(VaultFinderListService.java:46) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.vault.registry.VaultRegistryListService.list(VaultRegistryListService.java:68) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:62) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:37) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.WorkerBackgroundAction.run(WorkerBackgroundAction.java:70) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction.run(SessionBackgroundAction.java:122) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction$1.call(SessionBackgroundAction.java:106) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.DefaultRetryCallable.call(DefaultRetryCallable.java:52) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction.call(SessionBackgroundAction.java:108) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.BackgroundCallable.run(BackgroundCallable.java:96) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:60) [core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at ch.cyberduck.core.threading.DispatchExecutorService$InvocationFutureTask.run(DispatchExecutorService.java:281) ~[libcore-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
Caused by: java.util.concurrent.TimeoutException: Timeout expired: 15000 MILLISECONDS
	at net.schmizz.concurrent.Promise.retrieve(Promise.java:139) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.sftp.SFTPEngine.doRequest(SFTPEngine.java:146) ~[sshj-0.35.0.jar:?]
	at net.schmizz.sshj.sftp.SFTPEngine.openDir(SFTPEngine.java:169) ~[sshj-0.35.0.jar:?]
	at ch.cyberduck.core.sftp.SFTPListService.list(SFTPListService.java:61) ~[ssh-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.vault.VaultFinderListService.list(VaultFinderListService.java:46) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.vault.registry.VaultRegistryListService.list(VaultRegistryListService.java:68) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:62) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:37) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.WorkerBackgroundAction.run(WorkerBackgroundAction.java:70) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction.run(SessionBackgroundAction.java:122) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction$1.call(SessionBackgroundAction.java:106) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.DefaultRetryCallable.call(DefaultRetryCallable.java:52) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.SessionBackgroundAction.call(SessionBackgroundAction.java:108) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.BackgroundCallable.run(BackgroundCallable.java:96) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:60) ~[core-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at ch.cyberduck.core.threading.DispatchExecutorService$InvocationFutureTask.run(DispatchExecutorService.java:281) ~[libcore-8.6.3.jar:5de4863ac8abfe5b7c9fb95330beefb62c14b995]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) ~[rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
2023-09-06 08:37:08,355 [Thread-7049] INFO  ch.cyberduck.core.threading.SessionBackgroundAction - Run alert callback ch.cyberduck.ui.cocoa.callback.PromptAlertCallback@6ffc8579 for failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=Path{path='/home/user/webapps/themainpop/wp-content/themes/themainpop', type=[directory]}, message='Listing directory themainpop failed.', detail='Timeout expired: 15000 MILLISECONDS.', cause='net.schmizz.sshj.sftp.SFTPException: Timeout expired: 15000 MILLISECONDS'}
2023-09-06 08:37:08,355 [Thread-7049] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=Path{path='/home/user/webapps/themainpop/wp-content/themes/themainpop', type=[directory]}, message='Listing directory themainpop failed.', detail='Timeout expired: 15000 MILLISECONDS.', cause='net.schmizz.sshj.sftp.SFTPException: Timeout expired: 15000 MILLISECONDS'}
2023-09-06 08:37:08,356 [Thread-7049] DEBUG ch.cyberduck.core.notification.NotificationCenter - Schedule notification <NSUserNotification:0x139826770> { title: "Listing directory themainpop failed." informativeText: "MySERVER" actionButtonTitle: "(null)" identifier: c268897a-9a03-4573-9b66-d3fc132bda7e }
2023-09-06 08:37:08,377 [main] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure BackgroundException{class=class ch.cyberduck.core.exception.InteroperabilityException, file=Path{path='/home/user/webapps/themainpop/wp-content/themes/themainpop', type=[directory]}, message='Listing directory themainpop failed.', detail='Timeout expired: 15000 MILLISECONDS.', cause='net.schmizz.sshj.sftp.SFTPException: Timeout expired: 15000 MILLISECONDS'}
2023-09-06 08:37:08,377 [main] WARN  ch.cyberduck.core.Factory - No implementation given for factory ReachabilityDiagnosticsFactory
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidChangeBackingProperties for selector:windowDidChangeBackingProperties:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowWillMove for selector:windowWillMove:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowWillExitVersionBrowser for selector:windowWillExitVersionBrowser:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidUpdate for selector:windowDidUpdate:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidResize for selector:windowDidResize:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidMiniaturize for selector:windowDidMiniaturize:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidEnterFullScreen for selector:windowDidEnterFullScreen:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidExitFullScreen for selector:windowDidExitFullScreen:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidChangeOcclusionState for selector:windowDidChangeOcclusionState:
2023-09-06 08:37:08,393 [main] DEBUG org.rococoa.callback - No method windowDidMove for selector:windowDidMove:

**Comment by tatze96** [comment]
Based on the log snipped, it seems that the listing fails because the server doesn't answer in time on the sent request.

Please try if increasing the *Timeout for opening connection* within the Cyberduck preferences *Connection* tab resolves the connectivity issue.

**Comment by andrastudio** [comment]
@tatze96 I already tried that but the issue still exist.

**Comment by ricapag2409** [comment]
I'm already having this issue too, log attached.
[cyberduck.log](https://github.com/iterate-ch/cyberduck/files/13705835/cyberduck.log)
