### ISSUE TITLE
java.lang.NoClassDefFoundError: com.github.sardine.model.Multistatus$JaxbAccessorF_responsedescription

### ISSUE THREAD

**Issue by minfrin** [iterate-ch/cyberduck#15108]
**Describe the bug**

java.lang.NoClassDefFoundError reported in logs.

**To Reproduce**
1. Run mountain duck with a WebDAV drive
2. View debug logs file

```
2023-07-28 15:11:30,844 [Thread-0] DEBUG com.sun.xml.bind.v2.runtime.reflect.opt.Injector - duplicate class definition bug occured? Please report this : com/github/sardine/model/Multistatus$JaxbAccessorF_
responsedescription
java.lang.NoClassDefFoundError: com.github.sardine.model.Multistatus$JaxbAccessorF_responsedescription (type not found in Cyberduck.Protocols, Version=8.6.1.0, Culture=neutral, PublicKeyToken=null)
        at Java_java_lang_ClassLoader.defineClass1(Unknown Source) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:771) ~[?:1.8.0]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:653) ~[?:1.8.0]
        at java.lang.reflect.Method.invoke(Method.java:486) ~[?:1.8.0]
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:291) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.reflect.opt.Injector.inject(Injector.java:68) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:57) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:169) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:256) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.property.SingleElementLeafProperty.<init>(SingleElementLeafProperty.java:62) [Cyberduck.Protocols.DLL:2.3.3]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:414) ~[?:1.8.0]
        at com.sun.xml.bind.v2.runtime.property.PropertyFactory.create(PropertyFactory.java:99) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.<init>(ClassBeanInfoImpl.java:150) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getOrCreate(JAXBContextImpl.java:494) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:310) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1142) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:141) [Cyberduck.Protocols.DLL:2.3.3]
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:265) [Cyberduck.Protocols.DLL:2.3.3]
        at java.lang.reflect.Method.invoke(Method.java:486) ~[?:1.8.0]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:171) [?:1.8.0]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:131) [?:1.8.0]
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:335) [?:1.8.0]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:431) [?:1.8.0]
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:394) [?:1.8.0]
        at com.github.sardine.util.SardineUtil.<clinit>(SardineUtil.java:86) [Cyberduck.Protocols.DLL:5.14]
        at com.github.sardine.util.SardineUtil.createQNameWithDefaultNamespace(SardineUtil.java) [Cyberduck.Protocols.DLL:5.14]
        at ch.cyberduck.core.dav.DAVTimestampFeature.<clinit>(DAVTimestampFeature.java:49) [Cyberduck.Protocols.DLL:0c8ebea63600dea658d4530be92e95a69aadbd4c]
        at ch.cyberduck.core.dav.DAVTimestampFeature.<init>(DAVTimestampFeature.java) [Cyberduck.Protocols.DLL:0c8ebea63600dea658d4530be92e95a69aadbd4c]
        at ch.cyberduck.core.dav.DAVSession.<init>(DAVSession.java:93) [Cyberduck.Protocols.DLL:0c8ebea63600dea658d4530be92e95a69aadbd4c]
        at ch.cyberduck.core.dav.DAVSession.<init>(DAVSession.java:99) [Cyberduck.Protocols.DLL:0c8ebea63600dea658d4530be92e95a69aadbd4c]
```

**Expected behavior**
No exception reported

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 4.14.3

**Comment by AliveDevil** [comment]
This is an error in [IKVM](https://github.com/iterate-ch/ikvm), which is thrown and logged only when Debug-level is enabled, but doesn't have any impact on functionality.
