### ISSUE TITLE
cli.System.UriFormatException: Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by minfrin** [iterate-ch/cyberduck#15109]
**Describe the bug**
Exception reported on mountain duck start.

Mountain duck appears to be trying to connect to a blank URL, for reasons unknown.

**To Reproduce**
1. Open mountain duck debug log
2. See exception at top of log.

**Expected behavior**
No exception.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 4.14.3

**Log Files**

```
2023-08-29 10:39:56,046 [Thread-7] ERROR Ch.Cyberduck.Core.Diagnostics.TcpReachability - Generic exception while checking for reachability for Host{protocol=Profile{parent=davs, vendor=iterate GmbH, description=null, image=null}, region='null', port=443, hostname='', credentials=Credentials{user='', oauth='OAuthTokens{accessToken='', refreshToken='', expiryInMilliseconds=9223372036854775807}', token='', identity=null}, uuid='null', nickname='null', defaultpath='null', workdir=null, custom=null, labels=[]}
cli.System.UriFormatException: Invalid URI: The hostname could not be parsed.
        at cli.System.Uri.CreateThis(Unknown Source) ~[System.dll:?]
        at cli.System.Net.WebRequest.CreateHttp(Unknown Source) ~[System.dll:?]
        at cli.Ch.Cyberduck.Core.Diagnostics.TcpReachability.isReachable(Unknown Source) ~[Cyberduck.Core.Native.DLL:?]
        at java.lang.Throwable.getLocalizedMessage(map.xml:1230) ~[?:1.8.0]
        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:106) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:98) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:354) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:63) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:44) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.layout.PatternLayout$PatternFormatterPatternSerializer.toSerializable(PatternLayout.java:383) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.layout.PatternLayout.toText(PatternLayout.java:240) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:225) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.layout.PatternLayout.encode(PatternLayout.java:59) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:216) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:208) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:199) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.appender.RollingFileAppender.append(RollingFileAppender.java:302) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:136) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:90) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:682) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:643) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:626) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:560) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.core.Logger.log(Logger.java:163) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2168) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2122) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2105) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1981) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1948) [Cyberduck.Core.DLL:2.20.0]
        at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:719) [Cyberduck.Core.DLL:2.20.0]
        at cli.Ch.Cyberduck.Core.Diagnostics.TcpReachability.isReachable(Unknown Source) [Cyberduck.Core.Native.DLL:?]
```

**Comment by AliveDevil** [comment]
This is not an issue, per-se. What's the issue you are observing?

**Comment by minfrin** [comment]
We are debugging a crash that is taking out mountain duck, and these extra exceptions are making it hard to work out what's going on among the noise.

**Comment by AliveDevil** [comment]
Please collect all log files[^1], if not collected by our crash reporter[^1], but Windows in the event viewer applications list (source .NET Framework), and screenshots of error messages, and get in touch with the Mountain Duck support[^1] (support@mountainduck.io) with a description what action is causing a crash on your end.

[^1]: https://docs.mountainduck.io/mountainduck/support/

**Comment by minfrin** [comment]
The exception above is the very first entry in the log.

**Comment by AliveDevil** [comment]
There is a connectivity indicator in the bookmark configuration window, which, on TCP connection failure, show an exclamation mark icon, near the server field, to indicate that the server name/port pair may be invalid (due to either invalid DNS host name or non-responding TCP port).

This message is logged everytime something changed in the server name or port field - on every start of Mountain Duck without any configured bookmark - that is, the very first start of Mountain Duck usually doesn't have any bookmarks configured - an empty bookmark is created, and the configuration window shown.

As there is no default (i.e. an empty text) configured for the default WebDAV protocol, the aforementioned connectivity indicator tries to parse and connect to "", which fails, as "" is not a valid host name.

Additionally: The log file isn't recreated on every start (see timestamp: 2023-08-29), but appended, until it reaches 100 MiB of length, and only then it is rotated up to four times.

So: Please elaborate what crash you are experiencing, so we can investigate further.

**Comment by minfrin** [comment]
> There is a connectivity indicator in the bookmark configuration window, which, on TCP connection failure, show an exclamation mark icon, near the server field, to indicate that the server name/port pair may be invalid (due to either invalid DNS host name or non-responding TCP port).

We've been asked what that warning was, there was no tooltip on it so had no idea what it was referring to.

> So: Please elaborate what crash you are experiencing, so we can investigate further.

The crash is in the device driver of the smartcard, the problems we were having were isolating the errors around the crash that were related to the crash, and the noise in the log that were unrelated. Removing the noise makes the debugging process easier.

**Comment by AliveDevil** [comment]
Next Release/Snapshot of Cyberduck and Mountain Duck will just write
> WARN Reachability check for Host{protocol=Profile…} failed Invalid URI: The hostname could not be parsed.

Instead of printing the whole stack trace.

Additionally, on Mountain Duck Windows we'll filter out empty hostnames, so that these don't generate any more log entries.
