### ISSUE TITLE
MissingMethodException on Windows 10 Store

### ISSUE THREAD

**Issue by AliveDevil** [iterate-ch/cyberduck#15293]
```
System.MissingMethodException: Method not found: 'Windows.System.User
Windows.System.User.GetDefault()'.
at Ch.Cyberduck.Core.AquaticPrime.WindowsStoreLicense.getName()
at Ch.Cyberduck.Core.AquaticPrime.WindowsStoreLicense.ToString()
at Ch.Cyberduck.Ui.Winforms.BrowserForm..ctor()
at lambda_method(Closure , IArguments )
at
StructureMap.Construction.BuilderCompiler.FuncCompiler`1.<>c_DisplayClass2.<CreateBuilder>b_0(IArguments
args)
at StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType,
BuildSession session, IInstanceBuilder builder)
```

**Comment by dkocher** [comment]
Regression from 554671e.
