### ISSUE TITLE
Opening preferences causes "pt_BR is an invalid culture identifier" error

### ISSUE THREAD

**Issue by kirkd7** [iterate-ch/cyberduck#15330]
When opening Preferences the program shuts down.

Installed on WS 2019.

**Comment by dkocher** [comment]
Please attach the crash report found in `%AppData%\cyberduck\CrashReporter`.

**Comment by yoni-yad2** [comment]
It crashed also on my server when trying to open preferences window:

```
-----------------------------
[General Info]

Application: Cyberduck
Version:     8.7.1.40770
Region:      English (United States)
Date: 11/7/2023
Time: 9:11 AM

User Explanation:

User said ""
-----------------------------

[Exception Info 1]

Top-level Exception
Type:        System.Globalization.CultureNotFoundException
Message:     Culture is not supported.
Parameter name: name
pt_BR is an invalid culture identifier.
Source:      mscorlib
Stack Trace: at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Ch.Cyberduck.Core.Preferences.ApplicationPreferences.getDisplayName(String locale)
   at Ch.Cyberduck.Ui.Controller.PreferencesController.PopulateLanguages()
   at Ch.Cyberduck.Ui.Controller.PreferencesController.Init()
   at Ch.Cyberduck.Ui.Controller.PreferencesController..ctor(IPreferencesView view)
   at Ch.Cyberduck.Ui.Controller.PreferencesController.get_Instance()
   at Ch.Cyberduck.Ui.Controller.BrowserController.View_ShowPreferences()
   at Ch.Cyberduck.Ui.Core.Commands.Command.<>c__DisplayClass7_0.<.ctor>b__0(Object s, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Control.WmCommand(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

-----------------------------

[Assembly Info]

mscorlib, Version=4.0.0.0
System.Windows.Forms, Version=4.0.0.0
System, Version=4.0.0.0
System.Drawing, Version=4.0.0.0
Cyberduck.Core.Native, Version=8.7.1.40770
System.Memory, Version=4.0.1.1
Cyberduck.Core.Refresh, Version=8.7.1.40770
System.Core, Version=4.0.0.0
System.ServiceModel, Version=4.0.0.0
StructureMap, Version=2.6.4.0
Splat, Version=14.1.0.0
Cyberduck.Core, Version=8.7.1.40770
ObjectListView, Version=2.9.1.1072
CustomOpenFileFolderDialog, Version=0.0.0.0
WindowsFormsIntegration, Version=4.0.0.0
IKVM.OpenJDK.Core, Version=8.0.312.7
System.Design, Version=4.0.0.0
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1
Cyberduck.Bonjour.Native, Version=8.7.1.40770
System.Reactive, Version=5.0.0.0
System.Security, Version=4.0.0.0
Cyberduck.Protocols, Version=8.7.1.40770
ReactiveUI, Version=17.1.0.0
PresentationFramework, Version=4.0.0.0
Cyberduck.Importer, Version=8.7.1.40770
System.Xml, Version=4.0.0.0
Cyberduck.Bonjour, Version=8.7.1.40770
IKVM.Runtime, Version=8.0.312.7
ReactiveUI.Wpf, Version=17.1.0.0
PresentationCore, Version=4.0.0.0
Cyberduck.Cryptomator, Version=8.7.1.40770
IKVM.OpenJDK.Security, Version=8.0.312.7
IKVM.OpenJDK.Text, Version=8.0.312.7
DynamicData, Version=7.5.0.0
Windows.Services.Store.StoreContract, Version=4.0.0.0
System.Web, Version=4.0.0.0

-----------------------------

[System Info]

Operating System
-Microsoft Windows Server 2019 Standard
--CodeSet = 1255
--CSDVersion = 
--CurrentTimeZone = 120
--FreePhysicalMemory = 4700984
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.17763

Machine
-[Server Name]
--Manufacturer = Microsoft Corporation
--Model = Virtual Machine
--TotalPhysicalMemory = 33578541056

-----------------------------

```

**Comment by kirkd7** [comment]
Thanks,

I do have an install on a Windows 10 computer and no issues there.

 

I already moved the data off the server so will be using the W10 install going forward so not a blocking issue for me.

 

Kirk Diaz

JZK, Inc.

IT Manager

Office: 360.458.5211

Mobile: 360.960.0804

**Comment by AliveDevil** [comment]
Sorry for this unstable release (affects 8.7.0 and 8.7.1).
