### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by gfody** [iterate-ch/cyberduck#15332]
Cyberduck 8.7.0.40629 started throwing this error on startup:

![Untitled](https://github.com/iterate-ch/cyberduck/assets/1146032/946328ed-e3ea-4b59-b360-da2ddf5cb9a3)
Details:
```
System.MissingMethodException: Method not found: 'Windows.System.User Windows.System.User.GetDefault()'.
   at Ch.Cyberduck.Core.AquaticPrime.WindowsStoreLicense.getName()
   at Ch.Cyberduck.Core.AquaticPrime.WindowsStoreLicense.ToString()
   at Ch.Cyberduck.Ui.Winforms.BrowserForm..ctor()
   at lambda_method(Closure , IArguments )
   at StructureMap.Construction.BuilderCompiler.FuncCompiler`1.<>c__DisplayClass2.<CreateBuilder>b__0(IArguments args)
   at StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType, BuildSession session, IInstanceBuilder builder)
```

seems fine after reverting to 8.6.3.40040 maybe related to #15293?

**Desktop (please complete the following information):**
 - OS: Windows10 Version 22H2 (19045.3570)

**Comment by dkocher** [comment]
Duplicate for #15293. Please update to version 8.7.1 now available in Windows Store.
