### ISSUE TITLE
Cannot explore S3 paths that have consecutive slashes

### ISSUE THREAD

**Issue by weiatwork** [iterate-ch/cyberduck#15339]
This ticket system is to report bugs and feature requests. For support, visit the [help page](https://cyberduck.io/help/) first.

 * If you have trouble connecting to a server or your login credentials are not valid, try to resolve the issue with the assistance of your hosting service provider. Any such ticket will be closed with a resolution of _thirdparty_.

**Describe the bug**
When the S3 path is like "s3://mybucket/mydir//myfile" (note the double slashes between "mydir" and "myfile"), double-clicking "mydir" will report an error "File not found".

**To Reproduce**
1. Create a S3 path like above
2. Explore to "mydir" level
3. Double click "mydir"
4. See error "File not found"

**Expected behavior**
It should be able to either recognize the redundant slash(es) as separate folder(s), or skip it till a level where there is a "meaningful" folder.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 8.7.1

**Log Files**
```
2023-11-07 10:41:23,677 [Thread-230] WARN  ch.cyberduck.core.s3.S3ObjectListService - No placeholder found for directory Path{path='/mydir', type=[directory, placeholder]}
...
2023-11-07 10:41:23,677 [Thread-230] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure BackgroundException{class=class ch.cyberduck.core.exception.NotfoundException, file=null, message='File not found', detail='/mydir', cause='null'}
2023-11-07 10:41:23,677 [Thread-230] WARN  ch.cyberduck.core.threading.AbstractRetryCallable - No retry for failure BackgroundException{class=class ch.cyberduck.core.exception.NotfoundException, file=null, message='File not found', detail='/mydir', cause='null'}
2023-11-07 10:41:23,677 [Thread-230] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure running background task WorkerBackgroundAction{worker=SessionListWorker{directory=Path{path='/mydir', type=[directory, placeholder]}}}
java.lang.Exception: null
	at ch.cyberduck.core.threading.BackgroundCallable.<init>(BackgroundCallable.java:38) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.DefaultBackgroundExecutor.execute(DefaultBackgroundExecutor.java:81) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.AbstractController.background(AbstractController.java:72) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.reload(BrowserController.java:528) ~[osx-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.setWorkdir(BrowserController.java:3259) ~[osx-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.setWorkdir(BrowserController.java:3233) ~[osx-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.insideButtonClicked(BrowserController.java:2891) ~[osx-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$AbstractBrowserTableDelegate.tableRowDoubleClicked(BrowserController.java:3821) ~[osx-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) [rococoa-core-0.9.1.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) [jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) [jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:415) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:361) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.Function.invoke(Function.java:315) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at org.rococoa.internal.MsgSendHandler.invoke(MsgSendHandler.java:114) ~[rococoa-core-0.9.1.jar:?]
	at com.sun.jna.Library$Handler.invoke(Library.java:263) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at jdk.proxy2/jdk.proxy2.$Proxy5.syntheticSendMessage(Unknown Source) ~[?:?]
	at org.rococoa.Foundation.send(Foundation.java:207) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.Foundation.send(Foundation.java:181) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.sendOnThisOrMainThread(ObjCObjectInvocationHandler.java:245) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.invokeCocoa(ObjCObjectInvocationHandler.java:212) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.intercept(ObjCObjectInvocationHandler.java:171) ~[rococoa-core-0.9.1.jar:?]
	at ch.cyberduck.binding.application.NSApplication$$ByRococoa.run(<generated>) ~[binding-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.ui.cocoa.MainApplication.main(MainApplication.java:126) ~[osx-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
Caused by: ch.cyberduck.core.exception.NotfoundException: File not found
	at ch.cyberduck.core.s3.S3ObjectListService.list(S3ObjectListService.java:156) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.s3.S3ObjectListService.list(S3ObjectListService.java:71) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.s3.S3ObjectListService.list(S3ObjectListService.java:67) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.s3.S3ListService.list(S3ListService.java:82) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.s3.S3Session$9$1.call(S3Session.java:397) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.s3.S3Session$9$1.call(S3Session.java:394) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.s3.S3PathStyleFallbackAdapter.call(S3PathStyleFallbackAdapter.java:40) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.s3.S3Session$9.list(S3Session.java:399) ~[s3-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.vault.VaultFinderListService.list(VaultFinderListService.java:46) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.vault.registry.VaultRegistryListService.list(VaultRegistryListService.java:68) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:62) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.worker.SessionListWorker.run(SessionListWorker.java:37) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.WorkerBackgroundAction.run(WorkerBackgroundAction.java:70) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.SessionBackgroundAction.run(SessionBackgroundAction.java:122) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.SessionBackgroundAction$1.call(SessionBackgroundAction.java:106) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.DefaultRetryCallable.call(DefaultRetryCallable.java:52) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.SessionBackgroundAction.call(SessionBackgroundAction.java:108) ~[core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.BackgroundCallable.run(BackgroundCallable.java:96) [core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:60) [core-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at ch.cyberduck.core.threading.DispatchExecutorService$InvocationFutureTask.run(DispatchExecutorService.java:281) [libcore-8.7.1.jar:135d1b15821ad9ee5250f2ae37c2e9508f0151fe]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) ~[rococoa-core-0.9.1.jar:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:616) ~[jna-min-5.12.1.jar:5.12.1 (b0)]
2023-11-07 10:41:23,684 [Thread-230] INFO  ch.cyberduck.core.threading.SessionBackgroundAction - Run alert callback ch.cyberduck.ui.cocoa.callback.PromptAlertCallback@1c57e0e0 for failure BackgroundException{class=class ch.cyberduck.core.exception.NotfoundException, file=null, message='File not found', detail='/mydir', cause='null'}
```

**Additional context**

**Comment by dkocher** [comment]
Duplicate for #10981.
