### ISSUE TITLE
Program Crash during File Delete

### ISSUE THREAD

**Issue by kirkd7** [iterate-ch/cyberduck#15346]
Deleting multiple file form a folder crashes App, happened twice, this is the last crash report:
```
-----------------------------
[General Info]

Application: Cyberduck
Version:     8.7.1.40770
Region:      English (United States)
Date: 11/9/2023
Time: 12:46 AM

User Explanation:

User said ""
-----------------------------

[Exception Info 1]

Top-level Exception
Type:        System.NullReferenceException
Message:     Object reference not set to an instance of an object.
Source:      ObjectListView
Stack Trace: at BrightIdeasSoftware.TreeListView.TreeRenderer.HandleHitTest(Graphics g, OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   at BrightIdeasSoftware.BaseRenderer.HitTest(OlvListViewHitTestInfo hti, Int32 x, Int32 y)
   at BrightIdeasSoftware.ObjectListView.OlvHitTest(Int32 x, Int32 y)
   at BrightIdeasSoftware.ObjectListView.BuildCellEvent(CellEventArgs args, Point location)
   at BrightIdeasSoftware.ObjectListView.HandleMouseMove(Point pt)
   at BrightIdeasSoftware.ObjectListView.OnMouseMove(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseMove(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

-----------------------------

[Assembly Info]

mscorlib, Version=4.0.0.0
System.Windows.Forms, Version=4.0.0.0
System, Version=4.0.0.0
System.Drawing, Version=4.0.0.0
Cyberduck.Core.Native, Version=8.7.1.40770
System.Memory, Version=4.0.1.1
Cyberduck.Core.Refresh, Version=8.7.1.40770
System.Core, Version=4.0.0.0
System.ServiceModel, Version=4.0.0.0
StructureMap, Version=2.6.4.0
Splat, Version=14.1.0.0
Cyberduck.Core, Version=8.7.1.40770
ObjectListView, Version=2.9.1.1072
CustomOpenFileFolderDialog, Version=0.0.0.0
WindowsFormsIntegration, Version=4.0.0.0
IKVM.OpenJDK.Core, Version=8.0.312.7
System.Design, Version=4.0.0.0
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1
Cyberduck.Bonjour.Native, Version=8.7.1.40770
System.Reactive, Version=5.0.0.0
System.Security, Version=4.0.0.0
Cyberduck.Protocols, Version=8.7.1.40770
ReactiveUI, Version=17.1.0.0
PresentationFramework, Version=4.0.0.0
Cyberduck.Importer, Version=8.7.1.40770
System.Xml, Version=4.0.0.0
Cyberduck.Bonjour, Version=8.7.1.40770
IKVM.Runtime, Version=8.0.312.7
ReactiveUI.Wpf, Version=17.1.0.0
PresentationCore, Version=4.0.0.0
Cyberduck.Cryptomator, Version=8.7.1.40770
IKVM.OpenJDK.Security, Version=8.0.312.7
IKVM.OpenJDK.Text, Version=8.0.312.7
DynamicData, Version=7.5.0.0
Windows.Services.Store.StoreContract, Version=4.0.0.0
System.Web, Version=4.0.0.0

-----------------------------

[System Info]

Operating System
-Microsoft Windows 10 Pro for Workstations
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -480
--FreePhysicalMemory = 39280004
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.19045

Machine
-KIRKD
--Manufacturer = Dell Inc.
--Model = Precision 5820 Tower
--TotalPhysicalMemory = 68380434432

-----------------------------

```

**Comment by dkocher** [comment]
Duplicate for #10785.
