### ISSUE TITLE
When trying to enter Preferences the application crashes

### ISSUE THREAD

**Issue by puck** [iterate-ch/cyberduck#15493]
**Describe the bug**
When trying to enter Preferences the application crashes.

Downgrading to the previous version I had installed - 8.5.9 (39636) allows me to get into Preferences okay. Also works okay in 8.6.0 (39818) and 8.6.3 (40040).

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on Edit -> Preferences
2. Crash, with a window asking if I want to report the last crash. I have clicked on Send once, don't know if it was sent as nothing else happened.

**Expected behavior**
Entering the preferences window.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows Server 2019 Standard
 - Version: 8.7.1 (40770), 8.7.0 (40629)

**Log Files**
I can't find the log file, and I can't get into preferences to enable logging. But this in the crash file:

```
Top-level Exception
Type:        System.Globalization.CultureNotFoundException
Message:     Culture is not supported.
Parameter name: name
pt_BR is an invalid culture identifier.
Source:      mscorlib
Stack Trace: at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Ch.Cyberduck.Core.Preferences.ApplicationPreferences.getDisplayName(String locale)
   at Ch.Cyberduck.Ui.Controller.PreferencesController.PopulateLanguages()
   at Ch.Cyberduck.Ui.Controller.PreferencesController.Init()
   at Ch.Cyberduck.Ui.Controller.PreferencesController..ctor(IPreferencesView view)
   at Ch.Cyberduck.Ui.Controller.PreferencesController.get_Instance()
   at Ch.Cyberduck.Ui.Controller.BrowserController.View_ShowPreferences()
   at Ch.Cyberduck.Ui.Core.Commands.Command.<>c__DisplayClass7_0.<.ctor>b__0(Object s, EventArgs e)
   at System.Windows.Forms.MenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.MenuItem.MenuItemData.Execute()
   at System.Windows.Forms.Command.Invoke()
   at System.Windows.Forms.Control.WmCommand(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Additional context**

Cheers,
Andrew

**Comment by dkocher** [comment]
Duplicate for #15330.
