### ISSUE TITLE
Assembly reference mismatch causing crash when opening application

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/cyberduck#15535]
```
Top-level Exception
Type:        System.IO.FileLoadException
Message:     Could not load file or assembly 'System.Memory, Version=4.0.1.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
Source:      Cyberduck.Core.Refresh
Stack Trace: at Ch.Cyberduck.Core.Refresh.Media.Imaging.Icon`1..ctor(Stream stream)
   at Ch.Cyberduck.Core.Refresh.Services.WinFormsIconProvider.GetImages(Stream stream, GetCacheIconCallback getCache, CacheIconCallback cacheIcon, Boolean& dispose)
   at Ch.Cyberduck.Core.Refresh.Services.WinFormsIconProvider.Get(Object key, String path, String classifier, Boolean returnDefault, Image& default)
   at Ch.Cyberduck.Core.Refresh.Services.WinFormsIconProvider.GetDisk(Protocol protocol, Int32 size)
   at Ch.Cyberduck.Core.Refresh.Services.WinFormsIconProvider.BuildProtocolImageList()
   at Ch.Cyberduck.Core.Refresh.Services.WinFormsIconProvider..ctor(ProtocolFactory protocols, ProfileListObserver profileListObserver, IconCache iconCache, IIconProviderImageSource imageSource)
   at lambda_method(Closure , IArguments )
   at StructureMap.Construction.BuilderCompiler.FuncCompiler`1.<>c__DisplayClass2.<CreateBuilder>b__0(IArguments args)
   at StructureMap.Pipeline.ConstructorInstance.Build(Type pluginType, BuildSession session, IInstanceBuilder builder)
```

**Comment by dkocher** [comment]
Fix in bf2fb3b.

**Comment by AliveDevil** [comment]
Stack trace points to #15451 as regression, not #15524.

**Comment by AliveDevil** [comment]
Difficulty in observing this while developing:
Building in VS enables ProjectReferences to provide transient dependencies.
Due to the build infrastructure project reference building is disabled[^1]
[^1]: https://github.com/iterate-ch/cyberduck/blob/master/windows/build.xml#L60

So when building and running locally this is a non-issue, while CI will happily ignore newer references.
