### ISSUE TITLE
Cyberduck Crashes when I Upload a File into BigCommerce

### ISSUE THREAD

**Issue by cls295** [iterate-ch/cyberduck#16003]
Over the past month I have been having problems with Cyberduck crashing when I go to upload files. I reported a bug a few weeks ago and was told to delete all of the incomplete transfers out of Cyberduck and also my computer. I did this and it worked and I was able to transfer files without having any problems.

However, I recently updated Cyberduck and am having more problems with it crashing when I upload files. I checked and deleted all of the incomplete transfers and it is continuing to crash when I go to upload files. I am wondering what I can do to solve this problem?

Here is the Crash Report:

-----------------------------
[General Info]

Application: Cyberduck
Version:     8.5.8.39606
Region:      English (United States)
Date: 7/25/2023
Time: 1:32 PM

User Explanation:

User said ""
-----------------------------

[Exception Info 1]

Top-level Exception
Type:        java.lang.IllegalArgumentException
Message:     Illegal character in authority at index 8: https://WebDAV (HTTPS/SSL)/dav
Source:      IKVM.OpenJDK.Core
Stack Trace: at java.net.URI.create(String str)
   at ch.cyberduck.core.shared.DefaultUrlProvider.toUrl(Path file)
   at ch.cyberduck.core.vault.registry.VaultRegistryUrlProvider.toUrl(Path file)
   at ch.cyberduck.core.DefaulPromptUrlProvider.isSupported(Path file, Type type)
   at Ch.Cyberduck.Ui.Core.Commands.Command.Validate()
   at Ch.Cyberduck.Ui.Core.Commands.Validate()
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Ch.Cyberduck.Ui.Winforms.BaseForm.ShowDialog(IView owner)
   at Ch.Cyberduck.Ui.Controller.BrowserController.View_OpenConnection()
   at Ch.Cyberduck.Ui.Core.Commands.Command.<>c__DisplayClass6_0.<.ctor>b__1(Object s, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at Ch.Cyberduck.Ui.Winforms.Controls.ClickThroughToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Inner Exception 1
Type:        java.net.URISyntaxException
Message:     Illegal character in authority
Source:      IKVM.OpenJDK.Core
Stack Trace: at java.net.URI.Parser.fail(String , Int32 )
   at java.net.URI.Parser.parseAuthority(Int32 , Int32 )
   at java.net.URI.Parser.parseHierarchical(Int32 , Int32 )
   at java.net.URI.Parser.parse(Boolean )
   at java.net.URI..ctor(String str)
   at java.net.URI.create(String str)

-----------------------------

[Assembly Info]

mscorlib, Version=4.0.0.0
System.Windows.Forms, Version=4.0.0.0
System, Version=4.0.0.0
System.Drawing, Version=4.0.0.0
Cyberduck.Core.Native, Version=8.5.8.39606
System.Memory, Version=4.0.1.1
Cyberduck.Core.Refresh, Version=8.5.8.39606
System.Core, Version=4.0.0.0
System.ServiceModel, Version=4.0.0.0
StructureMap, Version=2.6.4.0
Splat, Version=14.1.0.0
Cyberduck.Core, Version=8.5.8.39606
ObjectListView, Version=2.9.1.1072
CustomOpenFileFolderDialog, Version=0.0.0.0
WindowsFormsIntegration, Version=4.0.0.0
IKVM.OpenJDK.Core, Version=8.0.312.7
System.Design, Version=4.0.0.0
System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0
Cyberduck.Bonjour.Native, Version=8.5.8.39606
System.Reactive, Version=5.0.0.0
System.Security, Version=4.0.0.0
Cyberduck.Protocols, Version=8.5.8.39606
ReactiveUI, Version=17.1.0.0
PresentationFramework, Version=4.0.0.0
Cyberduck.Importer, Version=8.5.8.39606
System.Xml, Version=4.0.0.0
Cyberduck.Bonjour, Version=8.5.8.39606
IKVM.Runtime, Version=8.0.312.7
PresentationCore, Version=4.0.0.0
ReactiveUI.Wpf, Version=17.1.0.0
Cyberduck.Cryptomator, Version=8.5.8.39606
IKVM.OpenJDK.Security, Version=8.0.312.7
IKVM.OpenJDK.Text, Version=8.0.312.7
System.Web, Version=4.0.0.0
Windows.Services.Store.StoreContract, Version=4.0.0.0

-----------------------------

[System Info]

Operating System
-Microsoft Windows 10 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -240
--FreePhysicalMemory = 11664336
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.19044

Machine
-INTERN-3
--Manufacturer = LENOVO
--Model = 11D1000NUS
--TotalPhysicalMemory = 16878100480

-----------------------------

**Comment by AliveDevil** [comment]
Hi, can you let share the bookmark configuration window for that particular bookmark?
Especially the additional properties section.

**Comment by cls295** [comment]
Thank you! I will go ahead and try the update, is this what you were looking for? If not could you send a picture to me of what you are looking for? It crashes as soon as I click the transfers tab now.
![Screenshot 2024-06-11 113516](https://github.com/iterate-ch/cyberduck/assets/162144993/26e5f7fb-2975-4ce4-bf4d-c4e3fe3f28ac)

**Comment by AliveDevil** [comment]
> crashes as soon as I click the transfers tab now

Clear out the folder `%AppData%\Cyberduck\Transfers` please.

**Comment by cls295** [comment]
Hi, I went ahead and cleared out all of the incomplete transfers out of the folder, and it did not end up working. I have cleared the incomplete transfers out of the folder and updated cyberduck multiple times now and it is still crashing.

Here is the Crash Report

[General Info]

Application: Cyberduck
Version:     8.9.0.41543+d02f1bfa2e5fbb472c231858583b9478a03210c9
Region:      English (United States)
Date: 6/19/2024
Time: 6:21 PM

User Explanation:

User said ""
-----------------------------

[Exception Info 1]

Top-level Exception
Type:        System.ArgumentException
Message:     Win32 handle that was passed to Icon is not valid or is the wrong type.
Source:      System.Drawing
Stack Trace: at System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   at System.Drawing.Icon.FromHandle(IntPtr handle)
   at Ch.Cyberduck.Core.Refresh.Services.WinFormsIconProvider.Get(IntPtr nativeIcon, CacheIconCallback cacheIcon)
   at Ch.Cyberduck.Core.Refresh.Services.IconProvider`1.GetFileIcon(String filename, Boolean isFolder, Boolean large, Boolean isExecutable)
   at Ch.Cyberduck.Ui.Controller.TransferController.UpdateIcon()
   at Ch.Cyberduck.Ui.Controller.TransferController.View_SelectionChangedEvent()
   at Ch.Cyberduck.Ui.Controller.VoidHandler.Invoke()
   at System.Windows.Forms.ListViewItemSelectionChangedEventHandler.Invoke(Object sender, ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at Ch.Cyberduck.Ui.Winforms.Controls.ListViewControls.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

-----------------------------

[Assembly Info]

mscorlib, Version=4.0.0.0
System.Windows.Forms, Version=4.0.0.0
System, Version=4.0.0.0
System.Drawing, Version=4.0.0.0
Cyberduck.Core.Refresh, Version=8.9.0.41543
Cyberduck.Core.Native, Version=8.9.0.41543
System.Memory, Version=4.0.1.2
System.Core, Version=4.0.0.0
Cyberduck.Core, Version=8.9.0.41543
System.ServiceModel, Version=4.0.0.0
StructureMap, Version=2.6.4.0
Splat, Version=14.1.0.0
ObjectListView, Version=2.9.1.1072
CustomOpenFileFolderDialog, Version=0.0.0.0
WindowsFormsIntegration, Version=4.0.0.0
IKVM.OpenJDK.Core, Version=8.0.312.7
System.Design, Version=4.0.0.0
System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1
Cyberduck.Bonjour.Native, Version=8.9.0.41543
System.Reactive, Version=5.0.0.0
System.Security, Version=4.0.0.0
Cyberduck.Protocols, Version=8.9.0.41543
ReactiveUI, Version=17.1.0.0
PresentationFramework, Version=4.0.0.0
Cyberduck.Importer, Version=8.9.0.41543
System.Xml, Version=4.0.0.0
Cyberduck.Bonjour, Version=8.9.0.41543
IKVM.Runtime, Version=8.0.312.7
ReactiveUI.Wpf, Version=17.1.0.0
PresentationCore, Version=4.0.0.0
Cyberduck.Cryptomator, Version=8.9.0.41543
IKVM.OpenJDK.Security, Version=8.0.312.7
IKVM.OpenJDK.Text, Version=8.0.312.7
DynamicData, Version=7.5.0.0
Windows.Services.Store.StoreContract, Version=4.0.0.0
System.Web, Version=4.0.0.0

-----------------------------

[System Info]

Operating System
-Microsoft Windows 11 Pro
--CodeSet = 1252
--CSDVersion = 
--CurrentTimeZone = -240
--FreePhysicalMemory = 7877100
--OSArchitecture = 64-bit
--OSLanguage = 1033
--ServicePackMajorVersion = 0
--ServicePackMinorVersion = 0
--Version = 10.0.22000

Machine
-INTERN-3
--Manufacturer = LENOVO
--Model = 11D1000NUS
--TotalPhysicalMemory = 16878100480

**Comment by cls295** [comment]
I have only been clearing out the incomplete transfers out of the folder in fear of losing the files that have been successfully uploaded to the website. What should I try next?

**Comment by AliveDevil** [comment]
```
Message: Win32 handle that was passed to Icon is not valid or is the wrong type.
    at Ch.Cyberduck.Core.Refresh.Services.IconProvider`1.GetFileIcon(String filename, Boolean isFolder, Boolean large, Boolean isExecutable)
```
We are trying to extract the file icon from some of your transfers, and that crashes.

Can you move the remaining transfers one by one out of the transfers folder (you may create a backup folder, and move them back, after identifiying the bad one), and when you found the culprit, send us the offending transfer file(s) to support@cyberduck.io?

You won't loose any files uploaded to your servers, this is just a history of past transfers.

**Comment by cls295** [comment]
Thank you so much I have a two questions before I send the offending Transfer Files.

1. If I do delete a file that has successfully transferred will it then permanently be removed from my website, which is where we place these documents?
2. Also, is there a limit on how many files we can have in CyberDuck?
