### ISSUE TITLE
Connecting to S3 with path style URL in v9.0.1

### ISSUE THREAD

**Issue by there-it-is** [iterate-ch/cyberduck#16176]
**Describe the bug**
No contents of s3 bucket after updating to 9.0.1

**To Reproduce**
1. Connect with your s3 bucket
2. S3 bucket gets listed but no folders and files
3. On clicking on the bucket the message "Reading of the configuration failed" gets shown
4. In comparison everything works perfect in version 9.0.0 of cyberduck

**Expected behavior**
All folders and files are visible

**Desktop:**
 - OS: macOS Sonoma 14.5

**Log Files**
Getting the message:
2024-07-24 14:59:25,024 [Thread-164] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure running background task WorkerBackgroundAction{worker=SessionListWorker{directory=Path{path='/mybucket', type=[directory, volume]}}}
java.lang.Exception: null
	at ch.cyberduck.core.threading.BackgroundCallable.<init>(BackgroundCallable.java:38) ~[core-9.0.1.jar:41dce8f1a9acc45a57a1217d4a5e5b7a90c3b70a]
…
Caused by: **java.net.UnknownHostException: mybucket.s3.mydomain.de**
	at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.14.jar:4.5.14]

**Additional context**
Used with S3 compatible NetApp StorageGRID and not AWS S3.
On opening the bucket cyberduck tries to connect to mybucket.s3.mydomain.de (virtual hosted style) but should instead connect to s3.mydomain.de/mybucket (path-style URL).

Would be nice to fix this problem like it was working in 9.0.0 or add a configuration for "path-style URL" or "virtual hosted style URL". 

Thanks Thomas

**Comment by dkocher** [comment]
Discussed in #16164.

**Comment by ylangisc** [comment]
Please [enable debugging logging](https://docs.cyberduck.io/cyberduck/support/#logging-output) and post the log file from a connection attempt with a bookmark backed by an S3 deprecated path style profile.

**Comment by there-it-is** [comment]
Oh thanks for the hint. I thought activating the profile in the settings is enough and missed the step to set the profile in the bookmark. With selecting "S3 (Deprecated path style request)" instead of "Amazon S3" it also works in Cyberduck v9.0.1
