### ISSUE TITLE
S3 deletion leads to many dialogue prompts claiming File-not-Found, but internally deletes the files

### ISSUE THREAD

**Issue by simon-clematide** [iterate-ch/cyberduck#16624]
When deleting a file on an s3 storage, there appears a dialog prompt for each file claiming that the 

**Describe the bug**
The file is removed, but a File not found dialogue is presented. 

**To Reproduce**
1. Try to delete one or several files on an s3 bucket.

**Expected behavior**
No dialogue should pop up. 

**Screenshots**
<img width="250" alt="image" src="https://github.com/user-attachments/assets/2452d98b-ad8a-40c8-8a1e-010830dd41ac">

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 9.1.1 (42521)

**Log Files**

```
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.vault.VaultFinderListProgressListener - Delay chunk notification for file listing of folder Path{path='HIDDENactionfem', type=[directory, placeholder]}
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.s3.RequestEntityRestStorageService - Set endpoint to os.zhdk.cloud.switch.ch
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.Jets3tProperties - s3service.disable-dns-buckets=false
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.s3.RequestEntityRestStorageService - Set hostname to HIDDEN.os.zhdk.cloud.switch.ch
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Added request parameter: encoding-type=url
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Added request parameter: max-keys=1
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Added request parameter: prefix=topics/topics-mallet-tm_2024_v2.0-multilingual_v2-0-1/actionfem
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Added request parameter: delimiter=/
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.s3.RequestEntityRestStorageService - Set URL to https://HIDDEN.os.zhdk.cloud.switch.ch:443/?encoding-type=url&max-keys=1&prefix=topics%2Ftopics-mallet-tm_2024_v2.0-multilingual_v2-0-1%2Factionfem&delimiter=%2F
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Performing GET request for 'https://HIDDEN.os.zhdk.cloud.switch.ch:443/?encoding-type=url&max-keys=1&prefix=topics%2Ftopics-mallet-tm_2024_v2.0-multilingual_v2-0-1%2Factionfem&delimiter=%2F', expecting response codes: [200]
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Headers: []
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.jets3t.service.Jets3tProperties - httpclient.retry-max=0
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
2024-12-06 17:59:43,231 [Thread-114] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.s3.S3Session - Use bucket name HIDDEN from context
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.s3.S3Session - Determined region null from URI https://HIDDEN.os.zhdk.cloud.switch.ch:443
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.s3.S3Session - Determined region null from Host{protocol=Profile{parent=s3, vendor=iterate GmbH, description=null, image=null}, region='null', port=443, hostname='os.zhdk.cloud.switch.ch', credentials=Credentials{user='ab92629cd6f14cda9f6964fcd168f132', password='', tokens='TemporaryAccessTokens{accessKeyId='', secretAccessKey='', sessionToken='', expiryInMilliseconds=9223372036854775807}', oauth='OAuthTokens{accessToken='', refreshToken='', idToken='', expiryInMilliseconds=9223372036854775807}', identity=null}, uuid='87006ff1-fef8-413b-8e87-ed27f08e4371', nickname='s3-switch-HIDDEN', defaultpath='/', workdir=Path{path='HIDDENactionfem', type=[directory, placeholder]}, custom={s3.location=us-east-1}, labels=null}
2024-12-06 17:59:43,231 [Thread-114] DEBUG ch.cyberduck.core.s3.S3Session - Determined region us-east-1 from defaults
2024-12-06 17:59:43,232 [Thread-114] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://HIDDEN.os.zhdk.cloud.switch.ch:443][total available: 3; route allocated: 2 of 2147483647; total allocated: 3 of 2147483647]
2024-12-06 17:59:43,232 [Thread-114] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection leased: [id: 5][route: {s}->https://HIDDEN.os.zhdk.cloud.switch.ch:443][total available: 2; route allocated: 2 of 2147483647; total allocated: 3 of 2147483647]
2024-12-06 17:59:43,232 [Thread-114] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-5: set socket timeout to 0
2024-12-06 17:59:43,232 [Thread-114] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-5: set socket timeout to 10000
2024-12-06 17:59:43,232 [Thread-114] DEBUG org.apache.http.impl.execchain.MainClientExec - Executing request GET /?encoding-type=url&max-keys=1&prefix=topics%2Ftopics-mallet-tm_2024_v2.0-multilingual_v2-0-1%2Factionfem&delimiter=%2F HTTP/1.1
2024-12-06 17:59:43,232 [Thread-114] DEBUG org.apache.http.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - GET /?encoding-type=url&max-keys=1&prefix=topics%2Ftopics-mallet-tm_2024_v2.0-multilingual_v2-0-1%2Factionfem&delimiter=%2F HTTP/1.1
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - Host: HIDDEN.os.zhdk.cloud.switch.ch
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - Connection: Keep-Alive
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - User-Agent: Cyberduck/9.1.1.42521 (Mac OS X/15.1.1) (aarch64)
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - Accept-Encoding: gzip,deflate
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - x-amz-date: 20241206T165943Z
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - x-amz-content-sha256: HIDDEN
2024-12-06 17:59:43,232 [Thread-114] INFO  ch.cyberduck.transcript.request - Authorization: ********
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - HTTP/1.1 200 OK
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - Server: nginx
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - Date: Fri, 06 Dec 2024 16:59:43 GMT
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - Content-Type: application/xml
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - Transfer-Encoding: chunked
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - Connection: keep-alive
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - x-amz-request-id: tx000005b276e5886de932d-0067532d7f-222b99f1d-default
2024-12-06 17:59:43,256 [Thread-114] INFO  ch.cyberduck.transcript.response - Strict-Transport-Security: max-age=31536000; includeSubdomains
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.apache.http.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Response for 'GET'. Content-Type: application/xml, Headers: [Server: nginx, Date: Fri, 06 Dec 2024 16:59:43 GMT, Content-Type: application/xml, Transfer-Encoding: chunked, Connection: keep-alive, x-amz-request-id: tx000005b276e5886de932d-0067532d7f-222b99f1d-default, Strict-Transport-Security: max-age=31536000; includeSubdomains]
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Response entity: ResponseEntityProxy{[Content-Type: application/xml,Chunked: true]}
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Entity length: -1
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Received response code 200; matches one of expected set ([200])? true
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.Jets3tProperties - xmlparser.sanitize-listings=false
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.XmlResponsesSaxParser - Parsing XML response document with handler: class org.jets3t.service.impl.rest.XmlResponsesSaxParser$ListBucketHandler
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.XmlResponsesSaxParser - Examining listing for bucket: HIDDEN
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection [id: 5][route: {s}->https://HIDDEN.os.zhdk.cloud.switch.ch:443] can be kept alive indefinitely
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.apache.http.impl.conn.DefaultManagedHttpClientConnection - http-outgoing-5: set socket timeout to 0
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager - Connection released: [id: 5][route: {s}->https://HIDDEN.os.zhdk.cloud.switch.ch:443][total available: 3; route allocated: 2 of 2147483647; total allocated: 3 of 2147483647]
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.HttpMethodReleaseInputStream - Released HttpMethod as its response data stream is fully consumed
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Found 0 objects in one batch
2024-12-06 17:59:43,257 [Thread-114] DEBUG org.jets3t.service.impl.rest.httpclient.RestStorageService - Found 0 common prefixes in one batch
2024-12-06 17:59:43,258 [Thread-114] WARN  ch.cyberduck.core.worker.ListWorker - Notify listener for Path{path='HIDDENactionfem', type=[directory, placeholder]} with error BackgroundException{class=class ch.cyberduck.core.exception.NotfoundException, file=null, message='File not found', detail='HIDDENactionfem', cause='null'}
2024-12-06 17:59:43,258 [Thread-114] WARN  ch.cyberduck.core.pool.StatelessSessionPool - Keep connection Session{host=Host{protocol=Profile{parent=s3, vendor=iterate GmbH, description=null, image=null}, region='null', port=443, hostname='os.zhdk.cloud.switch.ch', credentials=Credentials{user='ab92629cd6f14cda9f6964fcd168f132', password='', tokens='TemporaryAccessTokens{accessKeyId='', secretAccessKey='', sessionToken='', expiryInMilliseconds=9223372036854775807}', oauth='OAuthTokens{accessToken='', refreshToken='', idToken='', expiryInMilliseconds=9223372036854775807}', identity=null}, uuid='87006ff1-fef8-413b-8e87-ed27f08e4371', nickname='s3-switch-HIDDEN', defaultpath='/', workdir=Path{path='HIDDENactionfem', type=[directory, placeholder]}, custom={s3.location=us-east-1}, labels=null}, state=open} alive with failure BackgroundException{class=class ch.cyberduck.core.exception.NotfoundException, file=null, message='File not found', detail='HIDDENactionfem', cause='null'}
2024-12-06 17:59:43,258 [Thread-114] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure File not found
2024-12-06 17:59:43,258 [Thread-114] WARN  ch.cyberduck.core.threading.AbstractRetryCallable - No retry for failure File not found
2024-12-06 17:59:43,258 [Thread-114] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure overwriting cause for failure java.lang.Exception with BackgroundException{class=class ch.cyberduck.core.exception.NotfoundException, file=null, message='File not found', detail='HIDDENactionfem', cause='null'}
2024-12-06 17:59:43,258 [Thread-114] WARN  ch.cyberduck.core.threading.BackgroundCallable - Failure running background task WorkerBackgroundAction{worker=SessionListWorker{directory=Path{path='HIDDENactionfem', type=[directory, placeholder]}}}
java.lang.Exception: null
	at ch.cyberduck.core.threading.BackgroundCallable.<init>(BackgroundCallable.java:38) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.DefaultBackgroundExecutor.execute(DefaultBackgroundExecutor.java:70) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.AbstractController.background(AbstractController.java:72) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.reload(BrowserController.java:524) ~[osx-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.ui.cocoa.controller.BrowserController.reload(BrowserController.java:471) ~[osx-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.ui.cocoa.controller.BrowserController$27.done(BrowserController.java:2588) ~[osx-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.ui.cocoa.controller.DeleteController$1$1.cleanup(DeleteController.java:85) ~[osx-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.ui.cocoa.controller.DeleteController$1$1.cleanup(DeleteController.java:82) ~[osx-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.WorkerBackgroundAction.cleanup(WorkerBackgroundAction.java:85) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.BackgroundCallable$1.run(BackgroundCallable.java:64) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at org.rococoa.internal.MainThreadUtils$3.callback(MainThreadUtils.java:91) ~[rococoa-core-0.9.1.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) [jna-min-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:613) [jna-min-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.Native.invokeVoid(Native Method) ~[jna-min-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:418) ~[jna-min-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:364) ~[jna-min-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:318) ~[jna-min-5.14.0.jar:5.14.0 (b0)]
	at org.rococoa.internal.MsgSendHandler.invoke(MsgSendHandler.java:114) ~[rococoa-core-0.9.1.jar:?]
	at com.sun.jna.Library$Handler.invoke(Library.java:268) ~[jna-min-5.14.0.jar:5.14.0 (b0)]
	at jdk.proxy2/jdk.proxy2.$Proxy4.syntheticSendMessage(Unknown Source) ~[?:?]
	at org.rococoa.Foundation.send(Foundation.java:207) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.Foundation.send(Foundation.java:181) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.sendOnThisOrMainThread(ObjCObjectInvocationHandler.java:245) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.invokeCocoa(ObjCObjectInvocationHandler.java:212) ~[rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.ObjCObjectInvocationHandler.intercept(ObjCObjectInvocationHandler.java:171) ~[rococoa-core-0.9.1.jar:?]
	at ch.cyberduck.binding.application.NSApplication$$ByRococoa.run(<generated>) ~[binding-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.ui.cocoa.MainApplication.main(MainApplication.java:71) ~[osx-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
Caused by: ch.cyberduck.core.exception.NotfoundException: File not found
	at ch.cyberduck.core.s3.S3ObjectListService.list(S3ObjectListService.java:157) ~[s3-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.s3.S3ObjectListService.list(S3ObjectListService.java:71) ~[s3-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.s3.S3ObjectListService.list(S3ObjectListService.java:67) ~[s3-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.s3.S3ListService.listObjects(S3ListService.java:92) ~[s3-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.s3.S3ListService.list(S3ListService.java:74) ~[s3-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.vault.VaultFinderListService.list(VaultFinderListService.java:48) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.vault.registry.VaultRegistryListService.list(VaultRegistryListService.java:62) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.worker.ListWorker.run(ListWorker.java:64) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.worker.ListWorker.run(ListWorker.java:39) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.WorkerBackgroundAction.run(WorkerBackgroundAction.java:68) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.SessionBackgroundAction.run(SessionBackgroundAction.java:122) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.SessionBackgroundAction$1.call(SessionBackgroundAction.java:106) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.DefaultRetryCallable.call(DefaultRetryCallable.java:52) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.SessionBackgroundAction.call(SessionBackgroundAction.java:108) ~[core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.BackgroundCallable.run(BackgroundCallable.java:102) [core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at ch.cyberduck.core.threading.BackgroundCallable.call(BackgroundCallable.java:84) [core-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source) [?:?]
	at ch.cyberduck.core.threading.DispatchExecutorService$InvocationFutureTask.run(DispatchExecutorService.java:281) [libcore-9.1.1-SNAPSHOT.jar:2532f6026a5e545bf642add7a40f70670b88a367]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.rococoa.internal.OCInvocationCallbacks.callMethod(OCInvocationCallbacks.java:170) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks.access$200(OCInvocationCallbacks.java:52) [rococoa-core-0.9.1.jar:?]
	at org.rococoa.internal.OCInvocationCallbacks$2.callback(OCInvocationCallbacks.java:82) [rococoa-core-0.9.1.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.invokeCallback(CallbackReference.java:585) ~[jna-min-5.14.0.jar:5.14.0 (b0)]
	at com.sun.jna.CallbackReference$DefaultCallbackProxy.callback(CallbackReference.java:613) ~[jna-min-5.14.0.jar:5.14.0 (b0)]
2024-12-06 17:59:43,258 [Thread-114] INFO  ch.cyberduck.core.threading.SessionBackgroundAction - Run alert callback ch.cyberduck.ui.cocoa.callback.PromptAlertCallback@659c55de for failure BackgroundException{class=class ch.cyberduck.core.exception.NotfoundException, file=null, message='File not found', detail='HIDDENactionfem', cause='null'}
2024-12-06 17:59:43,258 [Thread-114] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure File not found
2024-12-06 17:59:43,258 [Thread-114] DEBUG ch.cyberduck.core.notification.NotificationCenter - Schedule notification <NSUserNotification:0x130fe4ee0> { title: "File not found" informativeText: "s3-switch-HIDDEN" actionButtonTitle: "(null)" identifier: 87006ff1-fef8-413b-8e87-ed27f08e4371 }
2024-12-06 17:59:43,265 [main] DEBUG ch.cyberduck.core.threading.DefaultFailureDiagnostics - Determine cause for failure File not found

```

**Comment by dkocher** [comment]
The error occurs after deleting the file and reloading the directory contents. It appears that `topics/topics-mallet-tm_2024_v2.0-multilingual_v2-0-1/actionfem` is 
* missing a directory placeholder file (a key named `topics/topics-mallet-tm_2024_v2.0-multilingual_v2-0-1/actionfem/`)
* no common prefix is returned for `GET /?encoding-type=url&max-keys=1&prefix=topics%2Ftopics-mallet-tm_2024_v2.0-multilingual_v2-0-1%2Factionfem&delimiter=%2F`

Therefore it is determined the directory does not exist and a _Not Found_ error is displayed.

Is `os.zhdk.cloud.switch.ch` a MinIO installation? Is it possible to get a temporary test account?
