### ISSUE TITLE
Deprecation warning for AWS dependency

### ISSUE THREAD

**Issue by dkocher** [iterate-ch/cyberduck#16660]
```
2024-12-11 14:17:55,485 [Thread-0] WARN  com.amazonaws.util.VersionInfoUtils - The AWS SDK for Java 1.x entered maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
You can print where on the file system the AWS SDK for Java 1.x core runtime is located by setting the AWS_JAVA_V1_PRINT_LOCATION environment variable or aws.java.v1.printLocation system property to 'true'.
This message can be disabled by setting the AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT environment variable or aws.java.v1.disableDeprecationAnnouncement system property to 'true'.
The AWS SDK for Java 1.x is being used here:
at java.lang.Thread.getStackTrace(Thread.java:1850)
at com.amazonaws.util.VersionInfoUtils.printDeprecationAnnouncement(VersionInfoUtils.java:81)
at com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:60)
at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java)
at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:95)
at ch.cyberduck.core.restore.Glacier.<init>(Glacier.java:60)
at ch.cyberduck.core.s3.S3Session.<init>(S3Session.java:113)
at java.lang.reflect.Constructor.newInstance(Constructor.java:414)
at ch.cyberduck.core.SessionFactory.create(SessionFactory.java:58)
at ch.cyberduck.core.SessionPoolFactory.create(SessionPoolFactory.java:103)
at ch.cyberduck.core.SessionPoolFactory.create(SessionPoolFactory.java:77)
at ch.cyberduck.core.SessionPoolFactory.create(SessionPoolFactory.java:65)
at ch.cyberduck.core.SessionPoolFactory.create(SessionPoolFactory.java:54)
at cli.Ch.Cyberduck.Ui.Controller.BrowserController$$$003C$$003Ec__DisplayClass222_0.<Mount>b__0(Unknown Source)
at cli.Ch.Cyberduck.Ui.Controller.BrowserController$$$003C$$003Ec__DisplayClass229_0.<UnmountImpl>b__0(Unknown Source)
at ch.cyberduck.core.threading.BackgroundCallable$1.run(BackgroundCallable.java:64)
at cli.System.Delegate.DynamicInvokeImpl(Unknown Source)
at cli.System.Windows.Forms.Control.InvokeMarshaledCallbackDo(Unknown Source)
at cli.System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Unknown Source)
at cli.System.Threading.ExecutionContext.RunInternal(Unknown Source)
at cli.System.Threading.ExecutionContext.Run(Unknown Source)
at cli.System.Threading.ExecutionContext.Run(Unknown Source)
at cli.System.Windows.Forms.Control.InvokeMarshaledCallback(Unknown Source)
at cli.System.Windows.Forms.Control.InvokeMarshaledCallbacks(Unknown Source)
at cli.System.Windows.Forms.Control.WndProc(Unknown Source)
at cli.System.Windows.Forms.Form.WndProc(Unknown Source)
at cli.System.Windows.Forms.NativeWindow.Callback(Unknown Source)
at cli.System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(Unknown Source)
at cli.System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(Unknown Source)
at cli.System.Windows.Forms.Application$ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Unknown Source)
at cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoopInner(Unknown Source)
at cli.System.Windows.Forms.Application$ThreadContext.RunMessageLoop(Unknown Source)
at cli.Ch.Cyberduck.Ui.Program.Main(Unknown Source)

```

**Comment by dkocher** [comment]
Depends on #13381.
